#!/usr/bin/env python3
"""
创建球队中文名称映射表
"""
import json

# 球队中文名称映射
TEAM_CHINESE_NAMES = {
    # 英格兰
    'Manchester City': '曼城',
    'Manchester United': '曼联',
    'Manchester City (ENG)': '曼城',
    'Manchester United (ENG)': '曼联',
    'Arsenal': '阿森纳',
    'Liverpool': '利物浦',
    'Chelsea': '切尔西',
    'Tottenham': '热刺',
    'Tottenham Hotspur': '热刺',
    'Newcastle': '纽卡斯尔',
    'Newcastle United': '纽卡斯尔',
    'Brighton': '布莱顿',
    'Brighton & Hove Albion': '布莱顿',
    'Aston Villa': '阿斯顿维拉',
    'West Ham': '西汉姆',
    'West Ham United': '西汉姆',
    'Crystal Palace': '水晶宫',
    'Wolves': '狼队',
    'Wolverhampton': '狼队',
    'Wolverhampton Wanderers': '狼队',
    'Leicester': '莱斯特城',
    'Leicester City': '莱斯特城',
    'Everton': '埃弗顿',
    'Leeds': '利兹联',
    'Leeds United': '利兹联',
    'Southampton': '南安普顿',
    'Burnley': '伯恩利',
    'Norwich': '诺维奇',
    'Norwich City': '诺维奇',
    'Watford': '沃特福德',
    'Bournemouth': '伯恩茅斯',
    'Fulham': '富勒姆',
    'Brentford': '布伦特福德',
    'Nottingham Forest': '诺丁汉森林',
    'Nottm Forest': '诺丁汉森林',
    'Luton': '卢顿',
    'Luton Town': '卢顿',
    'Sheffield United': '谢菲尔德联',
    'Sheffield Utd': '谢菲尔德联',
    'Ipswich': '伊普斯维奇',
    'Ipswich Town': '伊普斯维奇',

    # 德国
    'Bayern Munich': '拜仁慕尼黑',
    'Bayern': '拜仁慕尼黑',
    'Bayern Munchen': '拜仁慕尼黑',
    'Borussia Dortmund': '多特蒙德',
    'Dortmund': '多特蒙德',
    'B. Dortmund': '多特蒙德',
    'Bayer Leverkusen': '勒沃库森',
    'Leverkusen': '勒沃库森',
    'RB Leipzig': '莱比锡红牛',
    'Leipzig': '莱比锡红牛',
    'VfL Wolfsburg': '沃尔夫斯堡',
    'Wolfsburg': '沃尔夫斯堡',
    'Borussia Monchengladbach': '门兴格拉德巴赫',
    "M'gladbach": '门兴格拉德巴赫',
    'Monchengladbach': '门兴格拉德巴赫',
    'Eintracht Frankfurt': '法兰克福',
    'Frankfurt': '法兰克福',
    'SC Freiburg': '弗赖堡',
    'Freiburg': '弗赖堡',
    'TSG Hoffenheim': '霍芬海姆',
    'Hoffenheim': '霍芬海姆',
    'Mainz': '美因茨',
    'Mainz 05': '美因茨',
    'Union Berlin': '柏林联合',
    'VfB Stuttgart': '斯图加特',
    'Stuttgart': '斯图加特',
    'Werder Bremen': '云达不莱梅',
    'Bremen': '不莱梅',
    'Hertha Berlin': '柏林赫塔',
    'Hertha': '柏林赫塔',
    'Hertha BSC': '柏林赫塔',
    'Schalke': '沙尔克04',
    'Schalke 04': '沙尔克04',
    'FC Koln': '科隆',
    'Koln': '科隆',
    'Cologne': '科隆',
    'FC Augsburg': '奥格斯堡',
    'Augsburg': '奥格斯堡',
    'VfL Bochum': '波鸿',
    'Bochum': '波鸿',
    'Darmstadt': '达姆施塔特',
    'Heidenheim': '海登海姆',

    # 西班牙
    'Real Madrid': '皇家马德里',
    'Barcelona': '巴塞罗那',
    'Barca': '巴塞罗那',
    'Atletico Madrid': '马德里竞技',
    'Atletico': '马德里竞技',
    'Sevilla': '塞维利亚',
    'Seville': '塞维利亚',
    'Real Sociedad': '皇家社会',
    'Real Betis': '皇家贝蒂斯',
    'Betis': '贝蒂斯',
    'Villarreal': '比利亚雷亚尔',
    'Athletic': '毕尔巴鄂竞技',
    'Athletic Bilbao': '毕尔巴鄂竞技',
    'Valencia': '瓦伦西亚',
    'Getafe': '赫塔费',
    'Celta': '塞尔塔',
    'Celta Vigo': '塞尔塔',
    'Osasuna': '奥萨苏纳',
    'Mallorca': '马洛卡',
    'Rayo Vallecano': '巴列卡诺',
    'Cadiz': '加的斯',
    'Alaves': '阿拉维斯',
    'Girona': '赫罗纳',
    'Las Palmas': '拉斯帕尔马斯',
    'Almeria': '阿尔梅里亚',
    'Granada': '格拉纳达',
    'Espanyol': '西班牙人',

    # 意大利
    'Juventus': '尤文图斯',
    'Inter': '国际米兰',
    'Inter Milan': '国际米兰',
    'AC Milan': 'AC米兰',
    'Milan': 'AC米兰',
    'Napoli': '那不勒斯',
    'Naples': '那不勒斯',
    'Roma': '罗马',
    'AS Roma': '罗马',
    'Lazio': '拉齐奥',
    'Atalanta': '亚特兰大',
    'Fiorentina': '佛罗伦萨',
    'Bologna': '博洛尼亚',
    'Torino': '都灵',
    'Turin': '都灵',
    'Sassuolo': '萨索洛',
    'Udinese': '乌迪内斯',
    'Genoa': '热那亚',
    'Verona': '维罗纳',
    'Hellas Verona': '维罗纳',
    'Cagliari': '卡利亚里',
    'Lecce': '莱切',
    'Empoli': '恩波利',
    'Monza': '蒙扎',
    'Frosinone': '弗罗西诺内',
    'Salernitana': '萨勒尼塔纳',
    'Parma': '帕尔马',
    'Brescia': '布雷西亚',
    'Sampdoria': '桑普多利亚',

    # 法国
    'Paris SG': '巴黎圣日耳曼',
    'Paris Saint-Germain': '巴黎圣日耳曼',
    'PSG': '巴黎圣日耳曼',
    'Marseille': '马赛',
    'Lyon': '里昂',
    'Monaco': '摩纳哥',
    'AS Monaco': '摩纳哥',
    'AS Monaco (FRA)': '摩纳哥',
    'Lille': '里尔',
    'Nice': '尼斯',
    'Rennes': '雷恩',
    'Lens': '朗斯',
    'Montpellier': '蒙彼利埃',
    'Nantes': '南特',
    'Strasbourg': '斯特拉斯堡',
    'Toulouse': '图卢兹',
    'Bordeaux': '波尔多',
    'Reims': '兰斯',
    'Metz': '梅斯',
    'Le Havre': '勒阿弗尔',
    'Lorient': '洛里昂',
    'Clermont': '克莱蒙',
    'Brest': '布雷斯特',
    'Angers': '昂热',
    'Saint-Etienne': '圣埃蒂安',

    # 荷兰
    'Ajax': '阿贾克斯',
    'Ajax Amsterdam': '阿贾克斯',
    'PSV': '埃因霍温',
    'PSV Eindhoven': '埃因霍温',
    'Feyenoord': '费耶诺德',
    'AZ Alkmaar': '阿尔克马尔',
    'AZ': '阿尔克马尔',
    'Vitesse': '维特斯',
    'FC Twente': '特温特',
    'Twente': '特温特',
    'FC Utrecht': '乌得勒支',
    'Utrecht': '乌得勒支',
    'FC Groningen': '格罗宁根',
    'Groningen': '格罗宁根',
    'Heerenveen': '海伦芬',

    # 葡萄牙
    'Benfica': '本菲卡',
    'Porto': '波尔图',
    'FC Porto': '波尔图',
    'Sporting': '葡萄牙体育',
    'Sporting Lisbon': '葡萄牙体育',
    'Sporting CP': '葡萄牙体育',
    'Braga': '布拉加',

    # 土耳其
    'Galatasaray': '加拉塔萨雷',
    'Fenerbahce': '费内巴切',
    'Besiktas': '贝西克塔斯',
    'Trabzonspor': '特拉布宗体育',

    # 苏格兰
    'Celtic': '凯尔特人',
    'Rangers': '流浪者',
    'Aberdeen': '阿伯丁',
    'Hearts': '哈茨',
    'Hibernian': '希伯尼安',
    'Dundee United': '邓迪联',
    'Dundee Utd': '邓迪联',

    # 希腊
    'Olympiacos': '奥林匹亚科斯',
    'Panathinaikos': '帕纳辛奈科斯',
    'PAOK': '塞萨洛尼基',
    'AEK Athens': '雅典AEK',

    # 比利时
    'Club Brugge': '布鲁日',
    'Anderlecht': '安德莱赫特',
    'Genk': '亨克',
    'Gent': '根特',
    'Standard': '标准列日',
    'Standard Liege': '标准列日',

    # 奥地利
    'Salzburg': '萨尔茨堡红牛',
    'Red Bull Salzburg': '萨尔茨堡红牛',
    'RB Salzburg': '萨尔茨堡红牛',
    'Rapid Vienna': '维也纳快速',
    'Austria Vienna': '维也纳奥地利',

    # 瑞士
    'Young Boys': '年轻人',
    'Basel': '巴塞尔',
    'Zurich': '苏黎世',
    'FC Zurich': '苏黎世',

    # 俄罗斯
    'Zenit': '圣彼得堡泽尼特',
    'Zenit St Petersburg': '圣彼得堡泽尼特',
    'CSKA Moscow': '莫斯科中央陆军',
    'Spartak Moscow': '莫斯科斯巴达',
    'Lokomotiv Moscow': '莫斯科火车头',

    # 乌克兰
    'Shakhtar': '顿涅茨克矿工',
    'Shakhtar Donetsk': '顿涅茨克矿工',
    'Dynamo Kyiv': '基辅迪纳摩',
    'Dynamo Kiev': '基辅迪纳摩',

    # 巴西
    'Flamengo': '弗拉门戈',
    'Palmeiras': '帕尔梅拉斯',
    'Santos': '桑托斯',
    'Sao Paulo': '圣保罗',
    'Corinthians': '科林蒂安',
    'Gremio': '格雷米奥',
    'Internacional': '国际体育会',
    'Atletico Mineiro': '米内罗竞技',
    'Fluminense': '弗鲁米嫩塞',
    'Vasco': '瓦斯科达伽马',
    'Vasco da Gama': '瓦斯科达伽马',
    'Botafogo': '博塔弗戈',
    'Cruzeiro': '克鲁塞罗',

    # 阿根廷
    'Boca Juniors': '博卡青年',
    'River Plate': '河床',
    'River': '河床',
    'Racing Club': '竞技俱乐部',
    'Independiente': '独立队',
    'San Lorenzo': '圣洛伦索',

    # 墨西哥
    'Club America': '美洲俱乐部',
    'America': '美洲俱乐部',
    'Chivas': '瓜达拉哈拉',
    'Guadalajara': '瓜达拉哈拉',
    'Cruz Azul': '蓝十字',
    'Monterrey': '蒙特雷',
    'Tigres': '老虎大学',
    'Tigres UANL': '老虎大学',

    # 美国
    'LA Galaxy': '洛杉矶银河',
    'Seattle Sounders': '西雅图海湾人',
    'Atlanta United': '亚特兰大联',
    'NYCFC': '纽约城',
    'New York City': '纽约城',
    'New York City FC': '纽约城',
    'Toronto FC': '多伦多FC',
    'LAFC': '洛杉矶FC',
    'Los Angeles FC': '洛杉矶FC',
    'Inter Miami': '迈阿密国际',
    'Columbus Crew': '哥伦布机员',
    'Philadelphia Union': '费城联合',
    'New England': '新英格兰革命',
    'New England Revolution': '新英格兰革命',
    'Sporting KC': '堪萨斯城竞技',
    'Sporting Kansas City': '堪萨斯城竞技',
    'Portland Timbers': '波特兰伐木者',
    'Vancouver Whitecaps': '温哥华白帽',
    'Real Salt Lake': '皇家盐湖城',
    'FC Dallas': '达拉斯FC',
    'Houston Dynamo': '休斯顿迪纳摩',
    'San Jose Earthquakes': '圣何塞地震',
    'Colorado Rapids': '科罗拉多急流',
    'Minnesota United': '明尼苏达联',
    'Orlando City': '奥兰多城',
    'DC United': '华盛顿联',
    'Chicago Fire': '芝加哥火焰',
    'CF Montreal': '蒙特利尔',
    'Montreal': '蒙特利尔',
    'Charlotte FC': '夏洛特FC',
    'Austin FC': '奥斯汀FC',
    'St Louis City': '圣路易斯城',

    # 日本
    'Urawa Reds': '浦和红钻',
    'Urawa Red Diamonds': '浦和红钻',
    'Kashima Antlers': '鹿岛鹿角',
    'Yokohama F. Marinos': '横滨水手',
    'Yokohama Marinos': '横滨水手',
    'Kawasaki Frontale': '川崎前锋',
    'Gamba Osaka': '大阪钢巴',
    'Cerezo Osaka': '大阪樱花',
    'FC Tokyo': 'FC东京',
    'Tokyo': 'FC东京',

    # 韩国
    'Jeonbuk': '全北现代',
    'Jeonbuk Hyundai': '全北现代',
    'Suwon': '水原三星',
    'Suwon Samsung': '水原三星',
    'FC Seoul': 'FC首尔',
    'Seoul': 'FC首尔',
    'Pohang': '浦项制铁',
    'Pohang Steelers': '浦项制铁',

    # 沙特
    'Al Hilal': '利雅得新月',
    'Al Nassr': '利雅得胜利',
    'Al Ahli': '吉达联合',
    'Al Ittihad': '吉达国民',

    # 中国
    'Guangzhou': '广州队',
    'Guangzhou Evergrande': '广州恒大',
    'Shanghai SIPG': '上海海港',
    'Shanghai Port': '上海海港',
    'Beijing Guoan': '北京国安',
    'Shandong': '山东泰山',
    'Shandong Taishan': '山东泰山',
    'Shanghai Shenhua': '上海申花',

    # 澳大利亚
    'Sydney FC': '悉尼FC',
    'Melbourne City': '墨尔本城',
    'Melbourne Victory': '墨尔本胜利',
    'Western Sydney': '西悉尼流浪者',
    'Western Sydney Wanderers': '西悉尼流浪者',
    'Adelaide United': '阿德莱德联',
    'Central Coast': '中央海岸水手',
    'Central Coast Mariners': '中央海岸水手',
    'Perth Glory': '珀斯光荣',
    'Wellington': '惠灵顿凤凰',
    'Wellington Phoenix': '惠灵顿凤凰',

    # 非洲
    'Al Ahly': '开罗国民',
    'Zamalek': '扎马雷克',
    'Esperance': '突尼斯希望',
    'Esperance Tunis': '突尼斯希望',
    'Wydad': '卡萨布兰卡维达德',
    'Wydad Casablanca': '卡萨布兰卡维达德',
    'Mamelodi': '马梅洛迪日落',
    'Mamelodi Sundowns': '马梅洛迪日落',
    'Kaizer Chiefs': '凯泽酋长',
    'Orlando Pirates': '奥兰多海盗',

    # 国家队
    'Argentina': '阿根廷',
    'France': '法国',
    'Spain': '西班牙',
    'England': '英格兰',
    'Brazil': '巴西',
    'Netherlands': '荷兰',
    'Portugal': '葡萄牙',
    'Germany': '德国',
    'Colombia': '哥伦比亚',
    'Belgium': '比利时',
    'Italy': '意大利',
    'Croatia': '克罗地亚',
    'Uruguay': '乌拉圭',
    'Mexico': '墨西哥',
    'Switzerland': '瑞士',
    'USA': '美国',
    'United States': '美国',
    'Denmark': '丹麦',
    'Senegal': '塞内加尔',
    'Morocco': '摩洛哥',
    'Japan': '日本',
    'South Korea': '韩国',
    'Korea Republic': '韩国',
    'Australia': '澳大利亚',
    'Iran': '伊朗',
    'Saudi Arabia': '沙特阿拉伯',
    'China': '中国',
    'Russia': '俄罗斯',
    'Ukraine': '乌克兰',
    'Poland': '波兰',
    'Sweden': '瑞典',
    'Norway': '挪威',
    'Austria': '奥地利',
    'Czech Republic': '捷克',
    'Turkey': '土耳其',
    'Greece': '希腊',
    'Scotland': '苏格兰',
    'Wales': '威尔士',
    'Ireland': '爱尔兰',
    'Romania': '罗马尼亚',
    'Hungary': '匈牙利',
    'Serbia': '塞尔维亚',
    'Slovakia': '斯洛伐克',
    'Slovenia': '斯洛文尼亚',
    'Finland': '芬兰',
    'Iceland': '冰岛',
    'North Macedonia': '北马其顿',
    'Montenegro': '黑山',
    'Albania': '阿尔巴尼亚',
    'Bosnia': '波黑',
    'Bulgaria': '保加利亚',
    'Israel': '以色列',
    'Cyprus': '塞浦路斯',
    'Luxembourg': '卢森堡',
    'Kazakhstan': '哈萨克斯坦',
    'Azerbaijan': '阿塞拜疆',
    'Armenia': '亚美尼亚',
    'Georgia': '格鲁吉亚',
    'Belarus': '白俄罗斯',
    'Moldova': '摩尔多瓦',
    'Lithuania': '立陶宛',
    'Latvia': '拉脱维亚',
    'Estonia': '爱沙尼亚',
    'Malta': '马耳他',
    'Andorra': '安道尔',
    'Faroe Islands': '法罗群岛',
    'Gibraltar': '直布罗陀',
    'San Marino': '圣马力诺',
    'Liechtenstein': '列支敦士登',
    'Kosovo': '科索沃',
    'Chile': '智利',
    'Peru': '秘鲁',
    'Ecuador': '厄瓜多尔',
    'Paraguay': '巴拉圭',
    'Venezuela': '委内瑞拉',
    'Bolivia': '玻利维亚',
    'Canada': '加拿大',
    'Costa Rica': '哥斯达黎加',
    'Panama': '巴拿马',
    'Jamaica': '牙买加',
    'Honduras': '洪都拉斯',
    'El Salvador': '萨尔瓦多',
    'Trinidad': '特立尼达和多巴哥',
    'Trinidad and Tobago': '特立尼达和多巴哥',
    'Guatemala': '危地马拉',
    'Haiti': '海地',
    'Cuba': '古巴',
    'Nicaragua': '尼加拉瓜',
    'Egypt': '埃及',
    'Tunisia': '突尼斯',
    'Algeria': '阿尔及利亚',
    'Nigeria': '尼日利亚',
    'Cameroon': '喀麦隆',
    'Ghana': '加纳',
    'Ivory Coast': '科特迪瓦',
    "Cote d'Ivoire": '科特迪瓦',
    'South Africa': '南非',
    'Mali': '马里',
    'Congo': '刚果',
    'Guinea': '几内亚',
    'Zambia': '赞比亚',
    'Angola': '安哥拉',
    'Kenya': '肯尼亚',
    'Uganda': '乌干达',
    'Tanzania': '坦桑尼亚',
    'Zimbabwe': '津巴布韦',
    'Mozambique': '莫桑比克',
    'Gabon': '加蓬',
    'Burkina Faso': '布基纳法索',
    'Niger': '尼日尔',
    'Cape Verde': '佛得角',
    'Mauritania': '毛里塔尼亚',
    'Libya': '利比亚',
    'Sudan': '苏丹',
    'Togo': '多哥',
    'Benin': '贝宁',
    'Rwanda': '卢旺达',
    'Ethiopia': '埃塞俄比亚',
    'Madagascar': '马达加斯加',
    'Comoros': '科摩罗',
    'New Zealand': '新西兰',
    'Fiji': '斐济',
    'Papua New Guinea': '巴布亚新几内亚',
    'Solomon Islands': '所罗门群岛',
    'Vanuatu': '瓦努阿图',
    'North Korea': '朝鲜',
    'Korea DPR': '朝鲜',
    'Lebanon': '黎巴嫩',
    'Palestine': '巴勒斯坦',
    'Yemen': '也门',
    'Tajikistan': '塔吉克斯坦',
    'Kyrgyzstan': '吉尔吉斯斯坦',
    'Myanmar': '缅甸',
    'Singapore': '新加坡',
    'Hong Kong': '香港',
    'Taiwan': '台湾',
    'Chinese Taipei': '中华台北',
    'Thailand': '泰国',
    'Vietnam': '越南',
    'Indonesia': '印度尼西亚',
    'Malaysia': '马来西亚',
    'Philippines': '菲律宾',
    'India': '印度',
    'Qatar': '卡塔尔',
    'UAE': '阿联酋',
    'United Arab Emirates': '阿联酋',
    'Oman': '阿曼',
    'Bahrain': '巴林',
    'Kuwait': '科威特',
    'Jordan': '约旦',
    'Syria': '叙利亚',
    'Iraq': '伊拉克',
    'Uzbekistan': '乌兹别克斯坦',
}

# 联赛中文名称
LEAGUE_CHINESE_NAMES = {
    'Premier League': '英超',
    'Championship': '英冠',
    'League One': '英甲',
    'League Two': '英乙',
    'Bundesliga': '德甲',
    '2. Bundesliga': '德乙',
    '3. Liga': '德丙',
    'La Liga': '西甲',
    'Segunda Division': '西乙',
    'Serie A': '意甲',
    'Serie B': '意乙',
    'Ligue 1': '法甲',
    'Ligue 2': '法乙',
    'Eredivisie': '荷甲',
    'Eerste Divisie': '荷乙',
    'Belgian Pro League': '比甲',
    'Primeira Liga': '葡超',
    'Super Lig': '土超',
    '1. Lig': '土甲',
    'Ekstraklasa': '波兰超',
    'Eliteserien': '挪超',
    'Super League': '希腊超',
    'Scottish Premiership': '苏超',
    'Scottish Championship': '苏冠',
    'Scottish League One': '苏甲',
    'Scottish League Two': '苏乙',
    'Austrian Bundesliga': '奥地利超',
    '2. Liga': '奥地利甲',
    'Swiss Super League': '瑞士超',
    'Challenge League': '瑞士甲',
    'Russian Premier League': '俄超',
    'FNL': '俄甲',
    'Czech First League': '捷克甲',
    'NB I': '匈牙利甲',
    'Liga I': '罗马尼亚甲',
    'Ukrainian Premier League': '乌克兰超',
    'Croatian First League': '克罗地亚甲',
    'Slovak Super Liga': '斯洛伐克超',
    'Allsvenskan': '瑞典超',
    'Danish Superliga': '丹麦超',
    'Veikkausliiga': '芬超',
    'FA Cup': '英格兰足总杯',
    'EFL Cup': '英格兰联赛杯',
    'DFB-Pokal': '德国杯',
    'Copa del Rey': '西班牙国王杯',
    'Coppa Italia': '意大利杯',
    'Coupe de France': '法国杯',
    'UEFA Champions League': '欧冠',
    'UEFA Europa League': '欧联杯',
    'UEFA Conference League': '欧协杯',
    'FIFA World Cup': '世界杯',
    'World Cup Qualifiers': '世界杯预选赛',
    'UEFA European Championship': '欧洲杯',
    'Euro Qualifiers': '欧洲杯预选赛',
    'Copa America': '美洲杯',
    'Africa Cup of Nations': '非洲杯',
    'AFC Asian Cup': '亚洲杯',
    'CONCACAF Gold Cup': '中北美金杯',
    'UEFA Nations League': '欧洲国家联赛',
    'J1 League': '日职联',
    'J2 League': '日职乙',
    'K League 1': '韩K联',
    'K League 2': '韩K2联',
    'Chinese Super League': '中超',
    'A-League': '澳超',
    'Saudi Pro League': '沙特超',
    'AFC Champions League': '亚冠',
    'Campeonato Brasileiro Serie A': '巴甲',
    'Campeonato Brasileiro Serie B': '巴乙',
    'Argentine Primera Division': '阿甲',
    'Liga MX': '墨超',
    'Major League Soccer': '美职联',
    'Copa Libertadores': '南美解放者杯',
    'Egyptian Premier League': '埃及超',
}

# 国家中文名称
COUNTRY_CHINESE_NAMES = {
    'England': '英格兰',
    'Germany': '德国',
    'Spain': '西班牙',
    'Italy': '意大利',
    'France': '法国',
    'Netherlands': '荷兰',
    'Belgium': '比利时',
    'Portugal': '葡萄牙',
    'Turkey': '土耳其',
    'Greece': '希腊',
    'Norway': '挪威',
    'Poland': '波兰',
    'Austria': '奥地利',
    'Switzerland': '瑞士',
    'Russia': '俄罗斯',
    'Czech Republic': '捷克',
    'Hungary': '匈牙利',
    'Romania': '罗马尼亚',
    'Ukraine': '乌克兰',
    'Croatia': '克罗地亚',
    'Slovakia': '斯洛伐克',
    'Sweden': '瑞典',
    'Denmark': '丹麦',
    'Finland': '芬兰',
    'Scotland': '苏格兰',
    'Brazil': '巴西',
    'Argentina': '阿根廷',
    'Mexico': '墨西哥',
    'USA': '美国',
    'Japan': '日本',
    'South Korea': '韩国',
    'China': '中国',
    'Australia': '澳大利亚',
    'Saudi Arabia': '沙特阿拉伯',
    'Egypt': '埃及',
    'World': '世界',
    'Europe': '欧洲',
    'Asia': '亚洲',
    'South America': '南美洲',
    'North America': '北美洲',
    'Africa': '非洲',
}


def get_chinese_name(english_name, name_type='team'):
    """获取中文名称"""
    if name_type == 'team':
        return TEAM_CHINESE_NAMES.get(english_name, english_name)
    elif name_type == 'league':
        return LEAGUE_CHINESE_NAMES.get(english_name, english_name)
    elif name_type == 'country':
        return COUNTRY_CHINESE_NAMES.get(english_name, english_name)
    return english_name


def save_mapping_files():
    """保存映射文件"""
    output_dir = 'd:/football_tools/data/linkage'

    # 保存球队映射
    with open(f'{output_dir}/team_chinese_names.json', 'w', encoding='utf-8') as f:
        json.dump(TEAM_CHINESE_NAMES, f, ensure_ascii=False, indent=2)
    print(f"保存球队中文名称映射: {len(TEAM_CHINESE_NAMES)} 条")

    # 保存联赛映射
    with open(f'{output_dir}/league_chinese_names.json', 'w', encoding='utf-8') as f:
        json.dump(LEAGUE_CHINESE_NAMES, f, ensure_ascii=False, indent=2)
    print(f"保存联赛中文名称映射: {len(LEAGUE_CHINESE_NAMES)} 条")

    # 保存国家映射
    with open(f'{output_dir}/country_chinese_names.json', 'w', encoding='utf-8') as f:
        json.dump(COUNTRY_CHINESE_NAMES, f, ensure_ascii=False, indent=2)
    print(f"保存国家中文名称映射: {len(COUNTRY_CHINESE_NAMES)} 条")


if __name__ == '__main__':
    save_mapping_files()
