#!/usr/bin/env python3
"""
补充剩余球队中文名
"""

import sqlite3

DB_PATH = 'd:/football_tools/data/football_v2.db'

# 补充球队中文名
TEAM_CN_EXTRA = {
    # 英格兰低级别联赛
    'Walsall': '沃尔索尔', 'Swindon': '斯温登', 'Oxford': '牛津联',
    'Queens Park': '女王公园', 'Stranraer': '斯特兰拉尔',
    'Airdrie Utd': '艾德里联', 'Cove Rangers': '科夫流浪者',
    'Montrose': '蒙特罗斯', 'Brommapojkarna': '布罗马波伊卡纳',

    # 瑞典超
    'Halmstad': '哈尔姆斯塔德', 'Mjallby': '米亚尔比',
    'Degerfors': '代格福什', 'GAIS': '哥德堡盖斯',
    'Varnamo': '瓦尔纳莫', 'Västerås SK': '韦斯特罗斯',
    'Vasteras SK': '韦斯特罗斯', 'Orgryte': '奥格里特',
    'Örgryte': '奥格里特', 'Jaro': '雅罗',
    'Haka': '哈卡', 'KTP': '科特卡TP',
    'Ekenas': '埃克奈斯', 'EIF': '埃克奈斯',
    'Gnistan': '格尼斯坦', 'SJK': '塞伊奈约基',
    'IFK Mariehamn': '玛丽港', 'Mariehamn': '玛丽港',
    'AC Oulu': '奥卢', 'Oulu': '奥卢',
    'Ilves': '伊尔韦斯', 'Lahti': '拉赫蒂',
    'Inter Turku': '图尔库国际', 'VPS': '瓦萨',
    'TPS': '图尔库TPS', 'HIFK': '赫尔辛基IFK',

    # 荷兰
    'Zwolle': '兹沃勒', 'PEC Zwolle': '兹沃勒',
    'NAC': '布雷达', 'NAC Breda': '布雷达',
    'Telstar': '泰尔斯达', 'Dordrecht': '多德雷赫特',
    'FC Dordrecht': '多德雷赫特', 'TOP Oss': '奥斯',
    'MVV': '马斯特里赫特', 'MVV Maastricht': '马斯特里赫特',
    'Roda': '罗达JC', 'Roda JC': '罗达JC',
    'De Graafschap': '格拉夫沙普', 'Den Bosch': '登博斯',
    'FC Den Bosch': '登博斯', 'Helmond Sport': '海尔蒙德体育',
    'Eindhoven FC': '埃因霍温FC', 'Volendam': '沃伦丹',
    'FC Volendam': '沃伦丹', 'Excelsior': '鹿特丹精英',
    'Cambuur': '坎布尔', 'SC Cambuur': '坎布尔',
    'Almere City': '阿尔梅勒城', 'Willem II': '威廉二世',
    'Heracles': '赫拉克勒斯', 'Go Ahead': '埃因霍温前进',
    'Go Ahead Eagles': '埃因霍温前进', 'NEC': '奈梅亨',
    'NEC Nijmegen': '奈梅亨', 'RKC': '瓦尔韦克',
    'RKC Waalwijk': '瓦尔韦克', 'Sparta Rotterdam': '鹿特丹斯巴达',
    'Heerenveen': '海伦芬', 'SC Heerenveen': '海伦芬',
    'Groningen': '格罗宁根', 'FC Groningen': '格罗宁根',
    'Vitesse': '维特斯', 'Utrecht': '乌得勒支',
    'FC Utrecht': '乌得勒支', 'Twente': '特温特',
    'FC Twente': '特温特', 'AZ': '阿尔克马尔',
    'AZ Alkmaar': '阿尔克马尔', 'Feyenoord': '费耶诺德',
    'PSV': '埃因霍温', 'PSV Eindhoven': '埃因霍温',
    'Ajax': '阿贾克斯', 'For Sittard': '锡塔德幸运',
    'Fortuna Sittard': '锡塔德幸运', 'Sittard': '锡塔德',
    'Nijmegen': '奈梅亨', 'Waalwijk': '瓦尔韦克',

    # 意大利
    'Juve Stabia': '尤文图斯斯塔比亚', 'Stabia': '斯塔比亚',
    'FeralpiSalo': '费拉尔皮萨洛', 'Salò': '萨洛',
    'Mantova': '曼托瓦', 'Cesena': '切塞纳',
    'Carrarese': '卡拉雷塞', 'Avellino': '阿韦利诺',
    'Padova': '帕多瓦', 'Vicenza': '维琴察',
    'Ternana': '特尔纳纳', 'Catania': '卡塔尼亚',
    'Alessandria': '亚历山德里亚', 'Virtus Entella': '恩特拉',
    'Pordenone': '波代诺内', 'Pisa': '比萨',
    'AC Pisa': '比萨', 'Ascoli': '阿斯科利',
    'Cittadella': '奇塔代拉', 'Brescia': '布雷西亚',
    'Perugia': '佩鲁贾', 'Palermo': '巴勒莫',
    'Bari': '巴里', 'Modena': '摩德纳',
    'Reggina': '雷吉纳', 'Reggiana': '雷吉亚纳',
    'Catanzaro': '卡坦扎罗', 'Cosenza': '科森扎',
    'Sudtirol': '南蒂罗尔', 'Südtirol': '南蒂罗尔',
    'Lecco': '莱科', 'Como': '科莫',
    'Como 1907': '科莫', 'Venezia': '威尼斯',
    'Venezia FC': '威尼斯', 'Spezia': '斯佩齐亚',
    'Cremonese': '克雷莫纳', 'Sampdoria': '桑普多利亚',
    'Genoa': '热那亚', 'Cagliari': '卡利亚里',
    'Lecce': '莱切', 'Empoli': '恩波利',
    'Sassuolo': '萨索洛', 'Udinese': '乌迪内斯',
    'Monza': '蒙扎', 'Torino': '都灵',
    'Bologna': '博洛尼亚', 'Fiorentina': '佛罗伦萨',
    'Atalanta': '亚特兰大', 'Lazio': '拉齐奥',
    'Roma': '罗马', 'Napoli': '那不勒斯',
    'Juventus': '尤文图斯', 'Milan': 'AC米兰',
    'Inter': '国际米兰', 'Verona': '维罗纳',
    'Hellas Verona': '维罗纳', 'Genoa': '热那亚',
    'Parma': '帕尔马', 'Salernitana': '萨勒尼塔纳',
    'Frosinone': '弗罗西诺内',

    # 西班牙
    'Ceuta': '休达', 'AD Ceuta': '休达',
    'Cultural Leonesa': '伦昂萨文化', 'Leonesa': '伦昂萨',
    'Sociedad B': '皇家社会B队', 'Real Sociedad B': '皇家社会B队',
    'Bilbao Athletic': '毕尔巴鄂竞技B队', 'Athletic B': '毕尔巴鄂竞技B队',
    'Barcelona B': '巴萨B队', 'Barça B': '巴萨B队',
    'Real Madrid B': '皇马B队', 'Castilla': '卡斯蒂利亚',
    'Atletico Madrid B': '马竞B队', 'Atleti B': '马竞B队',
    'Valencia B': '瓦伦西亚B队', 'Villarreal B': '比利亚雷亚尔B队',
    'Sevilla B': '塞维利亚B队', 'Sevilla Atletico': '塞维利亚竞技',
    'Betis B': '贝蒂斯B队', 'Espanyol B': '西班牙人B队',
    'Girona B': '赫罗纳B队', 'Almeria B': '阿尔梅里亚B队',
    'Las Palmas B': '拉斯帕尔马斯B队', 'Tenerife B': '特内里费B队',
    'Albacete': '阿尔瓦塞特', 'Albacete BP': '阿尔瓦塞特',
    'Eldense': '埃尔登塞', 'CD Eldense': '埃尔登塞',
    'Cartagena': '卡塔赫纳', 'FC Cartagena': '卡塔赫纳',
    'Burgos': '布尔戈斯', 'Burgos CF': '布尔戈斯',
    'Mirandes': '米兰德斯', 'CD Mirandés': '米兰德斯',
    'Ibiza': '伊维萨', 'UD Ibiza': '伊维萨',
    'Andorra': '安道尔', 'FC Andorra': '安道尔FC',
    'Amorebieta': '阿莫雷别塔', 'SD Amorebieta': '阿莫尔别塔',
    'Ponferradina': '蓬费拉迪纳', 'SD Ponferradina': '蓬费拉迪纳',
    'Fuenlabrada': '富恩拉布拉达', 'CF Fuenlabrada': '富恩拉布拉达',
    'Alcorcon': '阿尔孔', 'AD Alcorcón': '阿尔孔',
    'Logroñés': '洛格罗涅斯', 'UD Logroñés': '洛格罗涅斯',
    'Badajoz': '巴达霍斯', 'CD Badajoz': '巴达霍斯',
    'Rayo Majadahonda': '马哈达翁达', 'Majadahonda': '马哈达翁达',
    'Atletico Baleares': '巴利阿里竞技', 'Baleares': '巴利阿里',
    'Linares': '利纳雷斯', 'Linares Deportivo': '利纳雷斯',
    'Algeciras': '阿尔赫西拉斯', 'Real Balompédica': '巴洛姆佩迪卡',
    'San Fernando': '圣费尔南多', 'San Fernando CD': '圣费尔南多',
    'Merida': '梅里达', 'Mérida': '梅里达',
    'Cornella': '科尔内利亚', 'UE Cornellà': '科尔内利亚',
    'Hercules': '大力神', 'Hércules': '大力神',
    'Elche': '埃尔切', 'Elche CF': '埃尔切',
    'Nastic': '塔拉戈纳', 'Gimnàstic': '塔拉戈纳',
    'Gimnastic': '塔拉戈纳', 'Tarragona': '塔拉戈纳',
    'Lugo': '卢戈', 'CD Lugo': '卢戈',
    'Alaves': '阿拉维斯', 'Alavés': '阿拉维斯',
    'Deportivo Alavés': '阿拉维斯', 'Leganes': '莱加内斯',
    'Leganés': '莱加内斯', 'Espanyol': '西班牙人',
    'Valladolid': '巴利亚多利德', 'Real Valladolid': '巴利亚多利德',
    'Girona': '赫罗纳', 'Girona FC': '赫罗纳',
    'Las Palmas': '拉斯帕尔马斯', 'UD Las Palmas': '拉斯帕尔马斯',
    'Mallorca': '马洛卡', 'RCD Mallorca': '马洛卡',
    'Rayo Vallecano': '巴列卡诺', 'Vallecano': '巴列卡诺',
    'Osasuna': '奥萨苏纳', 'CA Osasuna': '奥萨苏纳',
    'Getafe': '赫塔费', 'Getafe CF': '赫塔费',
    'Celta': '塞尔塔', 'RC Celta': '塞尔塔',
    'Celta Vigo': '塞尔塔', 'Almeria': '阿尔梅里亚',
    'UD Almería': '阿尔梅里亚', 'Almería': '阿尔梅里亚',
    'Cadiz': '加的斯', 'Cádiz': '加的斯',
    'Cádiz CF': '加的斯', 'Granada': '格拉纳达',
    'Granada CF': '格拉纳达', 'Elche': '埃尔切',
    'Levante': '莱万特', 'Levante UD': '莱万特',
    'Huesca': '韦斯卡', 'SD Huesca': '韦斯卡',
    'Eibar': '埃瓦尔', 'SD Eibar': '埃瓦尔',
    'Malaga': '马拉加', 'Málaga': '马拉加',
    'Málaga CF': '马拉加', 'Oviedo': '奥维耶多',
    'Real Oviedo': '奥维耶多', 'Sporting Gijon': '希洪竞技',
    'Sp Gijon': '希洪竞技', 'Gijón': '希洪',
    'Tenerife': '特内里费', 'CD Tenerife': '特内里费',
    'Santander': '桑坦德', 'Racing Santander': '桑坦德竞技',
    'Zaragoza': '萨拉戈萨', 'Real Zaragoza': '萨拉戈萨',
    'La Coruna': '拉科鲁尼亚', 'Dep. La Coruña': '拉科鲁尼亚',
    'Deportivo': '拉科鲁尼亚', 'Albacete': '阿尔瓦塞特',
    'Mirandes': '米兰德斯', 'Cartagena': '卡塔赫纳',
    'Burgos': '布尔戈斯', 'Eldense': '埃尔登塞',
    'Castellon': '卡斯特利翁', 'CD Castellón': '卡斯特利翁',
    'Ferrol': '费罗尔', 'Racing Ferrol': '费罗尔竞技',
    'Amorebieta': '阿莫雷别塔', 'Andorra': '安道尔',
    'Ibiza': '伊维萨', 'Ponferradina': '蓬费拉迪纳',
    'Fuenlabrada': '富恩拉布拉达', 'Alcorcon': '阿尔孔',
    'Lugo': '卢戈', 'Logroñés': '洛格罗涅斯',
    'Badajoz': '巴达霍斯',

    # 法国
    'Boulogne': '布洛涅', 'US Boulogne': '布洛涅',
    'Paris FC': '巴黎FC', 'Rodez': '罗德兹',
    'Rodez Aveyron': '罗德兹', 'Annecy': '阿讷西',
    'Bastia': '巴斯蒂亚', 'SC Bastia': '巴斯蒂亚',
    'AC Ajaccio': '阿雅克肖', 'Ajaccio': '阿雅克肖',
    'Pau FC': '波城', 'Dunkerque': '敦刻尔克',
    'USL Dunkerque': '敦刻尔克', 'Grenoble': '格勒诺布尔',
    'Grenoble Foot': '格勒诺布尔', 'Laval': '拉瓦勒',
    'Stade Lavallois': '拉瓦勒', 'Quevilly Rouen': '奎维利鲁昂',
    'US Quevilly-Rouen': '奎维利鲁昂', 'Amiens': '亚眠',
    'SC Amiens': '亚眠', 'Martigues': '马蒂格',
    'FC Martigues': '马蒂格', 'Troyes': '特鲁瓦',
    'ESTAC Troyes': '特鲁瓦', 'Concarneau': '孔卡尔诺',
    'US Concarneau': '孔卡尔诺', 'Niort': '尼奥尔',
    'Chamois Niortais': '尼奥尔', 'Nancy': '南锡',
    'AS Nancy': '南锡', 'Red Star': '红星',
    'FC Red Star': '红星', 'Vannes': '瓦讷',
    'Vannes OC': '瓦讷', 'Orléans': '奥尔良',
    'US Orléans': '奥尔良', 'Châteauroux': '沙托鲁',
    'LB Châteauroux': '沙托鲁', 'Le Mans': '勒芒',
    'Le Mans FC': '勒芒', 'Sochaux': '索肖',
    'FC Sochaux': '索肖', 'Valenciennes': '瓦朗谢讷',
    'US Valenciennes': '瓦朗谢讷', 'Caen': '卡昂',
    'SM Caen': '卡昂', 'Guingamp': '甘冈',
    'EA Guingamp': '甘冈', 'Lorient': '洛里昂',
    'FC Lorient': '洛里昂', 'Clermont': '克莱蒙',
    'Clermont Foot': '克莱蒙', 'Metz': '梅斯',
    'FC Metz': '梅斯', 'Saint-Étienne': '圣埃蒂安',
    'AS Saint-Étienne': '圣埃蒂安', 'St Etienne': '圣埃蒂安',
    'Angers': '昂热', 'Angers SCO': '昂热',
    'Auxerre': '欧塞尔', 'AJ Auxerre': '欧塞尔',
    'Le Havre': '勒阿弗尔', 'FC Le Havre': '勒阿弗尔',
    'Reims': '兰斯', 'Stade de Reims': '兰斯',
    'Brest': '布雷斯特', 'Stade Brestois': '布雷斯特',
    'Montpellier': '蒙彼利埃', 'MHSC': '蒙彼利埃',
    'Nantes': '南特', 'FC Nantes': '南特',
    'Toulouse': '图卢兹', 'TFC': '图卢兹',
    'Strasbourg': '斯特拉斯堡', 'Racing Strasbourg': '斯特拉斯堡',
    'Rennes': '雷恩', 'Stade Rennais': '雷恩',
    'Lens': '朗斯', 'RC Lens': '朗斯',
    'Nice': '尼斯', 'OGC Nice': '尼斯',
    'Lille': '里尔', 'LOSC': '里尔',
    'Monaco': '摩纳哥', 'AS Monaco': '摩纳哥',
    'Lyon': '里昂', 'Olympique Lyon': '里昂',
    'Marseille': '马赛', 'OM': '马赛',
    'PSG': '巴黎圣日耳曼', 'Paris Saint-Germain': '巴黎圣日耳曼',

    # 巴西
    'Clube do Remo': '雷莫', 'Remo': '雷莫',
    'Coritiba': '科里蒂巴', 'Coxa': '科里蒂巴',
    'Ponte Preta': '庞特普雷塔', 'Macaca': '庞特普雷塔',
    'Guarani': '瓜拉尼', 'Bugre': '瓜拉尼',
    'Operario': '奥佩拉里奥', 'Operário': '奥佩拉里奥',
    'Londrina': '隆德里纳', 'Tubarão': '隆德里纳',
    'Criciúma': '克里西乌马', 'Tigre': '克里西乌马',
    'Ituano': '伊图阿诺', 'Galo de Itu': '伊图阿诺',
    'Brusque': '布鲁斯克', 'Confianca': '康菲安卡',
    'Confiança': '康菲安卡', 'Nautico': '诺蒂科',
    'Náutico': '诺蒂科', 'Sampaio Correa': '桑帕约科雷亚',
    'Sampaio Corrêa': '桑帕约科雷亚', 'Vila Nova': '维拉诺瓦',
    'Goiania': '戈亚尼亚', 'CRB': '阿拉戈斯',
    'CSA': '阿拉戈斯体育', 'Juventude': '尤文图德',
    'Caxias': '卡西亚斯', 'Ypiranga': '伊皮兰加',
    'Brasil de Pelotas': '佩洛塔斯巴西', 'Pelotas': '佩洛塔斯',

    # 土耳其
    'Kocaelispor': '科贾埃利体育', 'Kocaeli': '科贾埃利',
    'Adanaspor': '阿达纳体育', 'Adana': '阿达纳',
    'Altay': '阿尔塔伊', 'Menemenspor': '梅内门体育',
    'Tuzlaspor': '图兹拉体育', 'Eyupspor': '埃尤普体育',
    'Bodrumspor': '博德鲁姆体育', 'Sakaryaspor': '萨卡里亚体育',
    'Giresunspor': '吉雷松体育', 'Umraniyespor': '乌姆拉尼耶体育',
    'Istanbulspor': '伊斯坦布尔体育', 'Yeni Malatyaspor': '新马拉蒂亚体育',
    'Altinordu': '阿尔丁奥尔杜', 'Bandirmaspor': '班德尔马体育',
    'Ankaraspor': '安卡拉体育', 'Erokspor': '埃罗克体育',

    # 挪威
    'KFUM Oslo': '奥斯陆KFUM', 'KFUM': 'KFUM',
    'Moss': '莫斯', 'Moss FK': '莫斯',
    'Kongsvinger': '孔斯温格', 'KIL': '孔斯温格',
    'Raufoss': '劳福斯', 'Ranheim': '兰海姆',
    'Sandnes Ulf': '桑内斯乌尔夫', 'Stjørdals-Blink': '斯蒂乌达尔布林克',
    'Levanger': '勒旺厄尔', 'Strømmen': '斯特罗门',
    'Ull/Kisa': '乌尔/基萨', 'Hamarkameratene': '哈马卡梅拉特内',
    'Bryne': '布赖讷', 'Fredrikstad': '腓特烈斯塔',
    'Stabæk': '斯塔贝克', 'Stabaek': '斯塔贝克',
    'Haugesund': '海于格松', 'FK Haugesund': '海于格松',
    'Kristiansund': '克里斯蒂安松', 'KBK': '克里斯蒂安松',
    'Aalesund': '奥勒松', 'AaFK': '奥勒松',
    'Sandefjord': '桑德菲尤德', 'Start': '斯达',
    'IK Start': '斯达', 'Jerv': '耶尔夫',
    'FK Jerv': '耶尔夫', 'Strømsgodset': '斯托姆加斯特',
    'Stromsgodset': '斯托姆加斯特', 'HamKam': '哈姆卡姆',
    'Ham-Kam': '哈姆卡姆', 'Lillestrøm': '利勒斯特罗姆',
    'Lillestrom': '利勒斯特罗姆', 'Tromsø': '特罗姆瑟',
    'Tromso': '特罗姆瑟', 'Bodø/Glimt': '博德闪耀',
    'Bodo/Glimt': '博德闪耀', 'Viking': '维京',
    'Viking FK': '维京', 'Brann': '布兰',
    'SK Brann': '布兰', 'Rosenborg': '罗森博格',
    'RBK': '罗森博格', 'Molde': '莫尔德',
    'Molde FK': '莫尔德', 'Valerenga': '瓦勒伦加',
    'Vålerenga': '瓦勒伦加', 'Sarpsborg 08': '萨尔普斯堡08',
    'Sarpsborg': '萨尔普斯堡', 'Odd': '奥德',
    'Odd BK': '奥德',

    # 葡萄牙
    'AVS': '阿韦斯', 'AVS Futebol': '阿韦斯',
    'Vila Real': '维拉Real', 'FC Vila Real': '维拉Real',
    'Oliveirense': '奥利维伦斯', 'UD Oliveirense': '奥利维伦斯',
    'Alverca': '阿尔韦尔卡', 'FC Alverca': '阿尔韦尔卡',
    'Leiria': '莱里亚', 'UD Leiria': '莱里亚',
    'Vilafranquense': '维拉弗兰昆塞', 'Amora': '阿莫拉',
    'Caldas': '卡尔达斯', 'Fátima': '法蒂玛',
    'Sertanense': '塞尔坦恩塞', 'Operário': '奥佩拉里奥',
    'Beira-Mar': '贝拉马尔', 'Académica': '阿卡迪米卡',
    'Académico Viseu': '维塞乌学院', 'Viseu': '维塞乌',
    'Trofense': '特罗芬斯', 'Sp. Covilhã': '科维良',
    'Covilhã': '科维良', 'Penafiel': '佩纳菲尔',
    'FC Penafiel': '佩纳菲尔', 'Feirense': '费伦斯',
    'CD Feirense': '费伦斯', 'Aves': '阿维斯',
    'Desportivo Aves': '阿维斯', 'Estoril': '埃斯托里尔',
    'GD Estoril Praia': '埃斯托里尔', 'Farense': '法伦斯',
    'SC Farense': '法伦斯', 'Portimonense': '波尔蒂莫嫩塞',
    'Portimonense SC': '波尔蒂莫嫩塞', 'Nacional': '国民队',
    'CD Nacional': '国民队', 'Santa Clara': '圣克拉拉',
    'Chaves': '沙维什', 'GD Chaves': '沙维什',
    'Vizela': '维塞拉', 'FC Vizela': '维塞拉',
    'Moreirense': '莫雷伦斯', 'Moreirense FC': '莫雷伦斯',
    'Arouca': '阿罗卡', 'FC Arouca': '阿罗卡',
    'Casa Pia': '卡萨皮亚', 'Casa Pia AC': '卡萨皮亚',
    'Estrela Amadora': '阿马多拉之星', 'Estrela': '阿马多拉之星',
    'Amadora': '阿马多拉', 'Gil Vicente': '吉尔维森特',
    'Gil Vicente FC': '吉尔维森特', 'Boavista': '博阿维斯塔',
    'Boavista FC': '博阿维斯塔', 'Rio Ave': '里奥阿维',
    'Rio Ave FC': '里奥阿维', 'Famalicão': '法马利康',
    'Famalicao': '法马利康', 'FC Famalicao': '法马利康',
    'Guimarães': '吉马良斯', 'Vitória Guimarães': '吉马良斯',
    'Vitoria SC': '吉马良斯', 'Vitória SC': '吉马良斯',
    'Braga': '布拉加', 'SC Braga': '布拉加',
    'Sp Braga': '布拉加', 'Sp Lisbon': '里斯本竞技',
    'Sporting CP': '里斯本竞技', 'Sporting': '里斯本竞技',
    'Porto': '波尔图', 'FC Porto': '波尔图',
    'Benfica': '本菲卡', 'SL Benfica': '本菲卡',
    'Maritimo': '马里蒂莫', 'CS Marítimo': '马里蒂莫',
    'Pacos Ferreira': '帕索斯费雷拉', 'Paços de Ferreira': '帕索斯费雷拉',
    'Tondela': '通德拉', 'GD Tondela': '通德拉',

    # 国家队补充
    'Hong Kong': '中国香港', 'Hong Kong, China': '中国香港',
    'Macao': '中国澳门', 'Macau': '中国澳门',
    'Chinese Taipei': '中华台北', 'Taiwan': '中华台北',
    'Guam': '关岛', 'Northern Mariana Islands': '北马里亚纳群岛',

    # 其他
    'A1': 'A1', 'A2': 'A2', 'A3': 'A3',
    'B1': 'B1', 'B2': 'B2', 'B3': 'B3',
    'C1': 'C1', 'C2': 'C2', 'C3': 'C3',
    'D1': 'D1', 'D2': 'D2', 'D3': 'D3',
    'E1': 'E1', 'E2': 'E2', 'E3': 'E3',
    'F1': 'F1', 'F2': 'F2', 'F3': 'F3',
    'W49': 'W49', 'W50': 'W50', 'W51': 'W51',
    'W52': 'W52', 'W53': 'W53', 'W54': 'W54',
    'W55': 'W55', 'W56': 'W56', 'W57': 'W57',
    'W58': 'W58', 'W59': 'W59', 'W60': 'W60',
    'W61': 'W61', 'W62': 'W62', 'W63': 'W63', 'W64': 'W64',
    'W89': 'W89', 'W90': 'W90', 'W91': 'W91',
    'W92': 'W92', 'W93': 'W93', 'W94': 'W94',
    'W95': 'W95', 'W96': 'W96', 'W97': 'W97',
    'W98': 'W98', 'W99': 'W99', 'W100': 'W100',
    'W101': 'W101', 'W102': 'W102',
    'L101': 'L101', 'L102': 'L102',
    'J1': 'J1', 'J3': 'J3',
    'K1': 'K1', 'K3': 'K3',
    'I1': 'I1', 'I3': 'I3',
}


def update_teams():
    print("补充剩余球队中文名...")
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    updated = 0
    for team_name, name_cn in TEAM_CN_EXTRA.items():
        cursor.execute('''
            UPDATE teams SET name_cn = ? WHERE name_en = ?
        ''', (name_cn, team_name))
        if cursor.rowcount > 0:
            updated += 1

    conn.commit()

    # 获取更新后状态
    cursor.execute('SELECT COUNT(*) FROM teams')
    total = cursor.fetchone()[0]
    cursor.execute('SELECT COUNT(*) FROM teams WHERE name_cn IS NOT NULL AND name_cn != ""')
    has_cn = cursor.fetchone()[0]

    print(f"  更新了 {updated} 个球队中文名")
    print(f"  当前: {has_cn}/{total} ({has_cn*100/total:.1f}%)")

    # 显示仍缺失的球队
    cursor.execute('SELECT name_en FROM teams WHERE name_cn IS NULL OR name_cn = "" ORDER BY name_en')
    missing = cursor.fetchall()
    if missing:
        print(f"\n仍有 {len(missing)} 个球队缺失中文名:")
        for t in missing[:20]:
            print(f"  {t[0]}")
        if len(missing) > 20:
            print(f"  ... 还有 {len(missing)-20} 个")

    conn.close()


if __name__ == '__main__':
    update_teams()
