#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
历史球星中文名词典
"""

import os
import sys
import sqlite3
from pathlib import Path

if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

PROJECT_ROOT = Path(__file__).parent.parent
DATABASE_PATH = PROJECT_ROOT / 'data' / 'football_v2.db'

# 历史球星中文名词典
PLAYER_NAMES = {
    # 阿根廷球星
    'Ariel Ortega': '奥特加',
    'Claudio Lopez': '克劳迪奥·洛佩斯',
    'Diego Placente': '普拉森特',
    'Diego Simeone': '西蒙尼',
    'Gabriel Batistuta': '巴蒂斯图塔',
    'Hernan Crespo': '克雷斯波',
    'Javier Zanetti': '萨内蒂',
    'Jose Chamot': '查莫特',
    'Juan Pablo Sorin': '索林',
    'Juan Sebastian Veron': '贝隆',
    'Kily Gonzalez': '基利·冈萨雷斯',
    'Matias Almeyda': '阿尔梅达',
    'Mauricio Pochettino': '波切蒂诺',
    'Pablo Aimar': '艾马尔',
    'Pablo Cavallero': '卡瓦列罗',
    'Walter Samuel': '萨穆埃尔',
    'Diego Maradona': '马拉多纳',
    'Lionel Messi': '梅西',
    'Sergio Aguero': '阿圭罗',
    'Gonzalo Higuain': '伊瓜因',
    'Angel Di Maria': '迪马利亚',
    'Ezequiel Lavezzi': '拉维奇',
    'Javier Mascherano': '马斯切拉诺',
    'Fernando Gago': '加戈',
    'Martin Demichelis': '德米凯利斯',
    'Nicolas Burdisso': '布尔迪索',
    'Gabriel Milito': '米利托',
    'Diego Milito': '迭戈·米利托',
    'Carlos Tevez': '特维斯',
    'Pablo Zabaleta': '萨巴莱塔',
    'Marcos Rojo': '罗霍',
    'Ezequiel Garay': '加雷',
    'Federico Fernandez': '费尔南德斯',
    'Ever Banega': '巴内加',
    'Lucas Biglia': '比格利亚',
    'Roberto Ayala': '阿亚拉',
    'Oscar Ruggeri': '鲁杰里',
    'Jorge Valdano': '巴尔达诺',
    'Ariel Holan': '霍兰',
    'Ricardo Bochini': '博奇尼',
    'Amadeo Carrizo': '卡里索',
    'Ubaldo Fillol': '菲洛尔',
    'Osvaldo Ardiles': '阿迪莱斯',
    'Mario Kempes': '肯佩斯',
    'Daniel Passarella': '帕萨雷拉',

    # 比利时球星
    'Bart Goor': '胡尔',
    'Branko Strupar': '斯特鲁帕尔',
    'Daniel Van Buyten': '范比滕',
    'Eric Van Meir': '范米尔',
    'Geert De Vlieger': '德弗利格',
    'Gert Verheyen': '费尔海恩',
    'Glen De Boeck': '德博克',
    'Jacky Peeters': '彼得斯',
    'Johan Walem': '瓦勒姆',
    'Marc Wilmots': '威尔莫茨',
    'Mbo Mpenza': '姆彭萨',
    'Nico Van Kerckhoven': '范凯克霍温',
    'Peter Van der Heyden': '范德海登',
    'Sven Vermant': '费尔曼特',
    'Timmy Simons': '西蒙斯',
    'Wesley Sonck': '松克',
    'Yves Vanderhaeghe': '范德哈格',
    'Eden Hazard': '阿扎尔',
    'Kevin De Bruyne': '德布劳内',
    'Romelu Lukaku': '卢卡库',
    'Thibaut Courtois': '库尔图瓦',
    'Vincent Kompany': '孔帕尼',
    'Jan Vertonghen': '维尔通亨',
    'Toby Alderweireld': '阿尔德韦雷尔德',
    'Axel Witsel': '维特塞尔',
    'Dries Mertens': '默滕斯',
    'Marouane Fellaini': '费莱尼',
    'Mousa Dembele': '穆萨·登贝莱',
    'Nacer Chadli': '沙兹利',
    'Yannick Carrasco': '卡拉斯科',
    'Thomas Meunier': '默尼耶',
    'Thorgan Hazard': '索尔根·阿扎尔',
    'Youri Tielemans': '蒂勒曼斯',
    'Charles De Ketelaere': '德凯特拉雷',
    'Jeremy Doku': '多库',
    'Amadou Onana': '奥纳纳',

    # 巴西球星
    'Pele': '贝利',
    'Ronaldo': '罗纳尔多',
    'Ronaldinho': '罗纳尔迪尼奥',
    'Rivaldo': '里瓦尔多',
    'Kaka': '卡卡',
    'Robinho': '罗比尼奥',
    'Adriano': '阿德里亚诺',
    'Diego': '迭戈',
    'Julio Baptista': '胡利奥·巴普蒂斯塔',
    'Maicon': '麦孔',
    'Dani Alves': '阿尔维斯',
    'Marcelo': '马塞洛',
    'Thiago Silva': '蒂亚戈·席尔瓦',
    'David Luiz': '大卫·路易斯',
    'Miranda': '米兰达',
    'Dante': '丹特',
    'Hernanes': '埃尔纳内斯',
    'Paulinho': '保利尼奥',
    'Fernandinho': '费尔南迪尼奥',
    'Luiz Gustavo': '古斯塔沃',
    'Willian': '威廉',
    'Oscar': '奥斯卡',
    'Bernard': '伯纳德',
    'Hulk': '胡尔克',
    'Fred': '弗雷德',
    'Jo': '若',
    'Julio Cesar': '胡利奥·塞萨尔',
    'Jefferson': '杰斐逊',
    'Victor': '维克托',
    'Dani Alves': '阿尔维斯',
    'Filipe Luis': '费利佩·路易斯',
    'Alex Sandro': '阿莱士·桑德罗',
    'Marquinhos': '马尔基尼奥斯',
    'Casemiro': '卡塞米罗',
    'Philippe Coutinho': '库蒂尼奥',
    'Neymar': '内马尔',
    'Gabriel Jesus': '热苏斯',
    'Alisson': '阿利松',
    'Ederson': '埃德森',
    'Roberto Firmino': '菲尔米诺',
    'Fabinho': '法比尼奥',
    'Richarlison': '理查利森',
    'Raphinha': '拉菲尼亚',
    'Vinicius Junior': '维尼修斯',
    'Rodrygo': '罗德里戈',
    'Antony': '安东尼',
    'Lucas Paqueta': '帕奎塔',
    'Bruno Guimaraes': '吉马良斯',

    # 法国球星
    'Zinedine Zidane': '齐达内',
    'Thierry Henry': '亨利',
    'Patrick Vieira': '维埃拉',
    'David Trezeguet': '特雷泽盖',
    'Robert Pires': '皮雷',
    'Sylvain Wiltord': '维尔托德',
    'Marcel Desailly': '德塞利',
    'Lilian Thuram': '图拉姆',
    'Bixente Lizarazu': '利扎拉祖',
    'Fabien Barthez': '巴特兹',
    'Laurent Blanc': '布兰科',
    'Emmanuel Petit': '佩蒂特',
    'Youri Djorkaeff': '德约卡夫',
    'Christophe Dugarry': '杜加里',
    'Frank Leboeuf': '勒伯夫',
    'Didier Deschamps': '德尚',
    'Alain Boghossian': '博戈西安',
    'Bernard Lama': '拉马',
    'Vincent Candela': '坎德拉',
    'Johan Micoud': '米库',
    'Nicolas Anelka': '阿内尔卡',
    'Louis Saha': '萨哈',
    'Djibril Cisse': '西塞',
    'William Gallas': '加拉',
    'Mikael Silvestre': '西尔韦斯特',
    'Willy Sagnol': '萨尼奥尔',
    'Gregory Coupet': '库佩',
    'Florent Malouda': '马卢达',
    'Franck Ribery': '里贝里',
    'Karim Benzema': '本泽马',
    'Nicolas Bendtner': '本特纳',
    'Samir Nasri': '纳斯里',
    'Hatem Ben Arfa': '本·阿尔法',
    'Yoann Gourcuff': '古尔库夫',
    'Jeremy Toulalan': '图拉朗',
    'Abou Diaby': '迪亚比',
    'Lassana Diarra': '拉萨纳·迪亚拉',
    'Patrice Evra': '埃弗拉',
    'Eric Abidal': '阿比达尔',
    'Gael Clichy': '克利希',
    'Bacary Sagna': '萨尼亚',
    'Laurent Koscielny': '科斯切尔尼',
    'Raphael Varane': '瓦拉内',
    'Paul Pogba': '博格巴',
    'Antoine Griezmann': '格列兹曼',
    'Kylian Mbappe': '姆巴佩',
    'Ousmane Dembele': '登贝莱',
    'N\'Golo Kante': '坎特',
    'Blaise Matuidi': '马图伊迪',
    'Corentin Tolisso': '托利索',
    'Thomas Lemar': '勒马尔',
    'Alexandre Lacazette': '拉卡泽特',
    'Anthony Martial': '马夏尔',
    'Kingsley Coman': '科曼',
    'Hugo Lloris': '洛里',
    'Steve Mandanda': '曼丹达',
    'Alphonse Areola': '阿雷奥拉',
    'Benjamin Pavard': '帕瓦尔',
    'Lucas Hernandez': '卢卡斯·埃尔南德斯',
    'Presnel Kimpembe': '金彭贝',
    'Clement Lenglet': '朗格莱',
    'Samuel Umtiti': '乌姆蒂蒂',
    'Adil Rami': '拉米',
    'Djibril Sidibe': '西迪贝',
    'Benjamin Mendy': '本杰明·门迪',
    'Ferland Mendy': '费兰·门迪',
    'Aurelien Tchouameni': '楚阿梅尼',
    'Eduardo Camavinga': '卡马文加',
    'William Saliba': '萨利巴',
    'Dayot Upamecano': '于帕梅卡诺',
    'Ibrahima Konate': '科纳特',
    'Jules Kounde': '孔德',
    'Mike Maignan': '迈尼昂',

    # 德国球星
    'Manuel Neuer': '诺伊尔',
    'Marc-Andre ter Stegen': '特尔施特根',
    'Kevin Trapp': '特拉普',
    'Antonio Rudiger': '吕迪格',
    'Matthias Ginter': '金特尔',
    'Niklas Sule': '聚勒',
    'Mats Hummels': '胡梅尔斯',
    'Jerome Boateng': '博阿滕',
    'Holger Badstuber': '巴德施图伯',
    'Per Mertesacker': '默特萨克',
    'Arne Friedrich': '弗里德里希',
    'Marcell Jansen': '扬森',
    'Philipp Lahm': '拉姆',
    'Bastian Schweinsteiger': '施魏因斯泰格',
    'Sami Khedira': '赫迪拉',
    'Thomas Muller': '穆勒',
    'Mesut Ozil': '厄齐尔',
    'Mario Gotze': '格策',
    'Julian Draxler': '德拉克斯勒',
    'Andre Schurrle': '许尔勒',
    'Toni Kroos': '克罗斯',
    'Mario Gomez': '戈麦斯',
    'Miroslav Klose': '克洛泽',
    'Lukas Podolski': '波多尔斯基',
    'Leroy Sane': '萨内',
    'Serge Gnabry': '格纳布里',
    'Kai Havertz': '哈弗茨',
    'Timo Werner': '维尔纳',
    'Jamal Musiala': '穆西亚拉',
    'Florian Wirtz': '维尔茨',
    'Joshua Kimmich': '基米希',
    'Leon Goretzka': '格雷茨卡',
    'Ilkay Gundogan': '京多安',
    'Emre Can': '埃姆雷·詹',
    'Jonathan Tah': '塔',
    'Nico Schlotterbeck': '施洛特贝克',
    'David Raum': '劳姆',
    'Christian Gunter': '金特',
    'Thilo Kehrer': '克雷尔',
    'Niklas Fulkrug': '菲尔克鲁格',

    # 意大利球星
    'Gianluigi Buffon': '布冯',
    'Dino Zoff': '佐夫',
    'Paolo Maldini': '马尔蒂尼',
    'Franco Baresi': '巴雷西',
    'Alessandro Costacurta': '科斯塔库塔',
    'Fabio Cannavaro': '卡纳瓦罗',
    'Alessandro Nesta': '内斯塔',
    'Giorgio Chiellini': '基耶利尼',
    'Leonardo Bonucci': '博努奇',
    'Andrea Barzagli': '巴尔扎利',
    'Marco Materazzi': '马特拉齐',
    'Fabio Grosso': '格罗索',
    'Gianluca Zambrotta': '赞布罗塔',
    'Andrea Pirlo': '皮尔洛',
    'Gennaro Gattuso': '加图索',
    'Daniele De Rossi': '德罗西',
    'Simone Perrotta': '佩罗塔',
    'Mauro Camoranesi': '卡莫拉内西',
    'Francesco Totti': '托蒂',
    'Alessandro Del Piero': '德尔·皮耶罗',
    'Luca Toni': '托尼',
    'Alberto Gilardino': '吉拉迪诺',
    'Vincenzo Iaquinta': '亚昆塔',
    'Filippo Inzaghi': '因扎吉',
    'Marco Di Vaio': '迪瓦约',
    'Antonio Cassano': '卡萨诺',
    'Giuseppe Rossi': '罗西',
    'Antonio Di Natale': '迪纳塔莱',
    'Fabio Quagliarella': '夸利亚雷拉',
    'Graziano Pelle': '佩莱',
    'Ciro Immobile': '因莫比莱',
    'Andrea Belotti': '贝洛蒂',
    'Lorenzo Insigne': '因西涅',
    'Domenico Berardi': '贝拉尔迪',
    'Federico Chiesa': '基耶萨',
    'Nicolo Zaniolo': '扎尼奥洛',
    'Sandro Tonali': '托纳利',
    'Nicolo Barella': '巴雷拉',
    'Manuel Locatelli': '洛卡特利',
    'Jorginho': '若日尼奥',
    'Marco Verratti': '维拉蒂',
    'Gianluigi Donnarumma': '多纳鲁马',
    'Mattia De Sciglio': '德希利奥',
    'Davide Calabria': '卡拉布里亚',
    'Alessandro Florenzi': '弗洛伦齐',
    'Giovanni Di Lorenzo': '迪洛伦佐',
    'Emerson Palmieri': '埃默松',
    'Federico Dimarco': '迪马尔科',
    'Rafael Leao': '莱奥',
    'Gianluca Scamacca': '斯卡马卡',

    # 荷兰球星
    'Edwin van der Sar': '范德萨',
    'Jasper Cillessen': '西莱森',
    'Tim Krul': '克鲁尔',
    'Michel Vorm': '弗姆',
    'Ron Vlaar': '弗拉尔',
    'Stefan de Vrij': '德弗里',
    'Bruno Martins Indi': '马丁斯·因迪',
    'Daley Blind': '布林德',
    'Gregory van der Wiel': '范德维尔',
    'Daryl Janmaat': '扬马特',
    'Paul Verhaegh': '费尔哈赫',
    'Terence Kongolo': '孔戈洛',
    'Memphis Depay': '德佩',
    'Arjen Robben': '罗本',
    'Wesley Sneijder': '斯内德',
    'Nigel de Jong': '德容',
    'Jonathan de Guzman': '德古兹曼',
    'Georginio Wijnaldum': '维纳尔杜姆',
    'Jordy Clasie': '克拉西',
    'Davy Klaassen': '克拉森',
    'Kevin Strootman': '斯特罗特曼',
    'Ibrahim Afellay': '阿费莱',
    'Jeremain Lens': '伦斯',
    'Quincy Promes': '普罗梅斯',
    'Klaas-Jan Huntelaar': '亨特拉尔',
    'Robin van Persie': '范佩西',
    'Dirk Kuyt': '库伊特',
    'Luuk de Jong': '卢克·德容',
    'Vincent Janssen': '扬森',
    'Virgil van Dijk': '范戴克',
    'Matthijs de Ligt': '德里赫特',
    'Frenkie de Jong': '德容',
    'Donny van de Beek': '范德贝克',
    'Steven Bergwijn': '贝格温',
    'Ryan Babel': '巴贝尔',
    'Nathan Ake': '阿克',
    'Patrick van Aanholt': '范安霍尔特',
    'Denzel Dumfries': '邓弗里斯',
    'Jurrien Timber': '廷伯',
    'Cody Gakpo': '加克波',
    'Xavi Simons': '哈维·西蒙斯',

    # 西班牙球星
    'Iker Casillas': '卡西利亚斯',
    'Victor Valdes': '巴尔德斯',
    'Pepe Reina': '雷纳',
    'David De Gea': '德赫亚',
    'Kepa Arrizabalaga': '凯帕',
    'Unai Simon': '乌奈·西蒙',
    'Carles Puyol': '普约尔',
    'Gerard Pique': '皮克',
    'Sergio Ramos': '拉莫斯',
    'Raul Albiol': '阿尔比奥尔',
    'Carlos Marchena': '马切纳',
    'Joan Capdevila': '卡普德维拉',
    'Alvaro Arbeloa': '阿韦洛亚',
    'Sergio Busquets': '布斯克茨',
    'Xabi Alonso': '阿隆索',
    'Xavi': '哈维',
    'Andres Iniesta': '伊涅斯塔',
    'David Silva': '大卫·席尔瓦',
    'Cesc Fabregas': '法布雷加斯',
    'Santi Cazorla': '卡索拉',
    'Juan Mata': '马塔',
    'Jesus Navas': '纳瓦斯',
    'Pedro': '佩德罗',
    'Fernando Torres': '托雷斯',
    'David Villa': '比利亚',
    'Fernando Llorente': '略伦特',
    'Alvaro Negredo': '内格雷多',
    'Diego Costa': '迭戈·科斯塔',
    'Alvaro Morata': '莫拉塔',
    'Rodrigo': '罗德里戈',
    'Mikel Oyarzabal': '奥亚萨瓦尔',
    'Marco Asensio': '阿森西奥',
    'Dani Olmo': '奥尔莫',
    'Ferran Torres': '费兰·托雷斯',
    'Ansu Fati': '法蒂',
    'Pedri': '佩德里',
    'Gavi': '加维',
    'Rodri': '罗德里',
    'Aymeric Laporte': '拉波尔特',
    'Pau Torres': '保·托雷斯',
    'Eric Garcia': '埃里克·加西亚',
    'Jose Gaya': '加亚',
    'Jordi Alba': '阿尔巴',
    'Dani Carvajal': '卡瓦哈尔',
    'Cesar Azpilicueta': '阿斯皮利奎塔',
    'Nacho Fernandez': '纳乔',
    'Marcos Llorente': '马科斯·略伦特',
    'Koke': '科克',
    'Thiago Alcantara': '蒂亚戈',
    'Saul Niguez': '萨乌尔',
    'Isco': '伊斯科',

    # 英格兰球星
    'David Seaman': '希曼',
    'Peter Shilton': '希尔顿',
    'Joe Hart': '乔·哈特',
    'Jordan Pickford': '皮克福德',
    'Nick Pope': '波普',
    'Aaron Ramsdale': '拉姆斯代尔',
    'Sam Johnstone': '约翰斯通',
    'Gareth Southgate': '索斯盖特',
    'Rio Ferdinand': '费迪南德',
    'John Terry': '特里',
    'Sol Campbell': '坎贝尔',
    'Jamie Carragher': '卡拉格',
    'Ledley King': '金',
    'Jonathan Woodgate': '伍德盖特',
    'Ashley Cole': '阿什利·科尔',
    'Wayne Bridge': '布里奇',
    'Gary Neville': '加里·内维尔',
    'Phil Neville': '菲尔·内维尔',
    'Steven Gerrard': '杰拉德',
    'Frank Lampard': '兰帕德',
    'Paul Scholes': '斯科尔斯',
    'David Beckham': '贝克汉姆',
    'Joe Cole': '乔·科尔',
    'Shaun Wright-Phillips': '赖特-菲利普斯',
    'Owen Hargreaves': '哈格里夫斯',
    'Michael Carrick': '卡里克',
    'Jermaine Jenas': '杰纳斯',
    'Scott Parker': '帕克',
    'Michael Owen': '欧文',
    'Wayne Rooney': '鲁尼',
    'Peter Crouch': '克劳奇',
    'Emile Heskey': '赫斯基',
    'Jermain Defoe': '迪福',
    'Theo Walcott': '沃尔科特',
    'Daniel Sturridge': '斯图里奇',
    'Danny Welbeck': '维尔贝克',
    'Harry Kane': '凯恩',
    'Jamie Vardy': '瓦尔迪',
    'Marcus Rashford': '拉什福德',
    'Raheem Sterling': '斯特林',
    'Jadon Sancho': '桑乔',
    'Phil Foden': '福登',
    'Bukayo Saka': '萨卡',
    'Jack Grealish': '格拉利什',
    'Mason Mount': '芒特',
    'Declan Rice': '赖斯',
    'Jude Bellingham': '贝林厄姆',
    'Kalvin Phillips': '菲利普斯',
    'Jordan Henderson': '亨德森',
    'Trent Alexander-Arnold': '阿诺德',
    'Kyle Walker': '沃克',
    'Kieran Trippier': '特里皮尔',
    'Luke Shaw': '卢克·肖',
    'Ben Chilwell': '奇尔韦尔',
    'Harry Maguire': '马奎尔',
    'John Stones': '斯通斯',
    'Eric Dier': '戴尔',
    'Conor Coady': '科迪',
    'Tyron Mings': '明斯',
    'Kyle Walker-Peters': '沃克-彼得斯',

    # 葡萄牙球星
    'Cristiano Ronaldo': 'C罗',
    'Luis Figo': '菲戈',
    'Rui Costa': '鲁伊·科斯塔',
    'Deco': '德科',
    'Nuno Valente': '努诺·瓦伦特',
    'Jorge Andrade': '安德拉德',
    'Ricardo Carvalho': '卡瓦略',
    'Fernando Meira': '梅拉',
    'Beto': '贝托',
    'Miguel': '米格尔',
    'Paulo Ferreira': '费雷拉',
    'Ricardo': '里卡多',
    'Bruno Alves': '布鲁诺·阿尔维斯',
    'Pepe': '佩佩',
    'Fabio Coentrao': '科恩特朗',
    'Joao Pereira': '若昂·佩雷拉',
    'Ricardo Costa': '里卡多·科斯塔',
    'Miguel Veloso': '维洛索',
    'Raul Meireles': '梅雷莱斯',
    'Tiago': '蒂亚戈',
    'Joao Moutinho': '穆蒂尼奥',
    'Nani': '纳尼',
    'Simao Sabrosa': '西芒',
    'Helder Postiga': '波斯蒂加',
    'Hugo Almeida': '阿尔梅达',
    'Liedson': '列德松',
    'Danny': '丹尼',
    'Ricardo Quaresma': '夸雷斯马',
    'Eder': '埃德尔',
    'Bernardo Silva': '贝尔纳多·席尔瓦',
    'Joao Mario': '若昂·马里奥',
    'Andre Gomes': '安德烈·戈麦斯',
    'Renato Sanches': '雷纳托·桑切斯',
    'William Carvalho': '威廉·卡瓦略',
    'Adrien Silva': '阿德里安·席尔瓦',
    'Bruno Fernandes': '布鲁诺·费尔南德斯',
    'Diogo Jota': '若塔',
    'Joao Felix': '若昂·菲利克斯',
    'Andre Silva': '安德烈·席尔瓦',
    'Goncalo Ramos': '贡萨洛·拉莫斯',
    'Rafael Leao': '莱奥',
    'Ruben Dias': '鲁本·迪亚斯',
    'Jose Fonte': '丰特',
    'Raphael Guerreiro': '格雷罗',
    'Nelson Semedo': '塞梅多',
    'Diogo Dalot': '达洛特',
    'Nuno Mendes': '努诺·门德斯',
    'Rui Patricio': '帕特里西奥',
    'Diogo Costa': '迪奥戈·科斯塔',

    # 乌拉圭球星
    'Diego Forlan': '弗兰',
    'Luis Suarez': '苏亚雷斯',
    'Edinson Cavani': '卡瓦尼',
    'Fernando Muslera': '穆斯莱拉',
    'Diego Lugano': '卢加诺',
    'Diego Godin': '戈丁',
    'Andres Scotti': '斯科蒂',
    'Martin Caceres': '卡塞雷斯',
    'Maximiliano Pereira': '佩雷拉',
    'Jorge Fucile': '富西莱',
    'Alvaro Pereira': '阿尔瓦罗·佩雷拉',
    'Sebastian Coates': '科茨',
    'Egidio Arevalo Rios': '阿雷瓦洛',
    'Walter Gargano': '加加诺',
    'Diego Perez': '迭戈·佩雷斯',
    'Sebastian Eguren': '埃古伦',
    'Nicolas Lodeiro': '洛代罗',
    'Alvaro Gonzalez': '阿尔瓦罗·冈萨雷斯',
    'Cristian Rodriguez': '罗德里格斯',
    'Abel Hernandez': '埃尔南德斯',
    'Sebastian Abreu': '阿布鲁',
    'Carlos Sanchez': '卡洛斯·桑切斯',
    'Jose Maria Gimenez': '希门尼斯',
    'Lucas Torreira': '托雷拉',
    'Rodrigo Bentancur': '本坦库尔',
    'Federico Valverde': '巴尔韦德',
    'Ronald Araujo': '阿劳霍',
    'Darwin Nunez': '努涅斯',

    # 非洲球星
    'Samuel Eto\'o': '埃托奥',
    'Didier Drogba': '德罗巴',
    'Yaya Toure': '亚亚·图雷',
    'Kolo Toure': '科洛·图雷',
    'Michael Essien': '埃辛',
    'John Obi Mikel': '米克尔',
    'Nwankwo Kanu': '卡努',
    'Jay-Jay Okocha': '奥科查',
    'Emmanuel Adebayor': '阿德巴约',
    'Asamoah Gyan': '吉安',
    'Sulley Muntari': '蒙塔里',
    'Kevin-Prince Boateng': '博阿滕',
    'Mohamed Salah': '萨拉赫',
    'Sadio Mane': '马内',
    'Riyad Mahrez': '马赫雷斯',
    'Pierre-Emerick Aubameyang': '奥巴梅扬',
    'Victor Osimhen': '奥斯梅恩',
    'Rafael Leao': '莱奥',
    'Achraf Hakimi': '阿什拉夫',
    'Hakim Ziyech': '齐耶赫',
    'Riyad Mahrez': '马赫雷斯',
    'Ismael Bennacer': '本纳塞尔',
    'Franck Kessie': '凯西',
    'Nicolas Pepe': '佩佩',
    'Eric Bailly': '拜利',
    'Wilfried Zaha': '扎哈',
    'Thomas Partey': '帕尔特伊',
    'Victor Moses': '摩西',
    'Odion Ighalo': '伊哈洛',
    'Ahmed Musa': '穆萨',
    'Wilfried Ndidi': '恩迪迪',
    'Kelechi Iheanacho': '伊希纳乔',
    'Samuel Kalu': '卡卢',
    'Victor Osimhen': '奥斯梅恩',
}


def translate_players():
    """翻译球员名"""
    print("=" * 60)
    print("Translating Historical Player Names")
    print("=" * 60)

    conn = sqlite3.connect(DATABASE_PATH)
    cursor = conn.cursor()

    translated = 0
    not_found = 0

    for en_name, cn_name in PLAYER_NAMES.items():
        cursor.execute(
            "UPDATE players SET name_cn = ?, updated_at = datetime('now') WHERE name_en = ? AND name_cn IS NULL",
            (cn_name, en_name)
        )
        if cursor.rowcount > 0:
            translated += 1
            print(f"  {en_name} -> {cn_name}")
        else:
            not_found += 1

    conn.commit()

    # 统计
    cursor.execute("SELECT COUNT(*) FROM players WHERE name_cn IS NOT NULL")
    total_cn = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(*) FROM players")
    total = cursor.fetchone()[0]

    conn.close()

    print(f"\nTranslated: {translated}")
    print(f"Not found in DB: {not_found}")
    print(f"Total with Chinese: {total_cn}/{total} ({total_cn/total*100:.1f}%)")


if __name__ == '__main__':
    translate_players()
