#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
更多球员中文名词典 - 按国家分类
"""

import os
import sys
import sqlite3
from pathlib import Path

if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

PROJECT_ROOT = Path(__file__).parent.parent
DATABASE_PATH = PROJECT_ROOT / 'data' / 'football_v2.db'

# 更多球员中文名词典
PLAYER_NAMES = {
    # 西班牙球员
    'Andres Garcia': '安德烈斯·加西亚',
    'Dean Huijsen': '惠森',
    'Marc Guiu': '吉乌',
    'Robert Sanchez': '罗伯特·桑切斯',
    'Jorge Cuenca': '昆卡',
    'Nicolas Gonzalez': '尼古拉斯·冈萨雷斯',
    'Alex Moreno': '亚历克斯·莫雷诺',
    'Sergio Reguilon': '雷吉隆',
    'Adrian Rodriguez': '阿德里安·罗德里格斯',
    'Ander Guevara': '格瓦拉',
    'Antonio Blanco': '布兰科',
    'Antonio Sivera': '西韦拉',
    'Asier Villalibre': '比利亚利布雷',
    'Carles Alena': '阿莱尼亚',
    'Carlos Martin': '卡洛斯·马丁',
    'Carlos Vicente': '卡洛斯·维森特',
    'Hugo Novoa': '诺沃亚',
    'Joan Jordan': '霍尔丹',
    'Jon Guridi': '古里迪',
    'Luis Rioja': '里奥哈',
    'Manu Sanchez': '马努·桑切斯',
    'Toni Martinez': '托尼·马丁内斯',
    'Adama Boiro': '博伊罗',
    'Ander Herrera': '埃雷拉',
    'Andoni Gorosabel': '戈罗萨韦尔',
    'Gorka Guruzeta': '古鲁泽塔',
    'Inigo Lekue': '莱库埃',
    'Inigo Ruiz de Galarreta': '鲁伊斯·德·加拉雷塔',
    'Javi Marton': '马顿',
    'Julen Agirrezabala': '阿吉雷萨瓦拉',
    'Mikel Vesga': '韦斯加',
    'Oihan Sancet': '桑塞特',
    'Unai Gomez': '乌奈·戈麦斯',
    'Unai Nunez': '努涅斯',
    'Yeray Alvarez': '耶赖·阿尔瓦雷斯',
    'Yuri Berchiche': '贝尔奇切',
    'Alex Berenguer': '贝伦格尔',
    'Mikel Jauregizar': '豪雷吉萨尔',
    'Beñat Prados': '普拉多斯',
    'Endika Bujan': '布汉',
    'Aitor Paredes': '帕雷德斯',
    'Alex Padilla': '帕迪利亚',
    'Nicolás Serrano': '塞拉诺',
    'Peio Canales': '卡纳莱斯',
    'Adu Ares': '阿杜·阿雷斯',
    'Aingeru Olabarrieta': '奥拉巴列塔',
    'Pau Cabanes': '卡瓦内斯',
    'Pica': '皮卡',
    'Stoichkov': '斯托伊奇科夫',
    'Kike': '基克',
    'Iago Aspas': '阿斯帕斯',
    'Borja Iglesias': '伊格莱西亚斯',
    'Santi Mina': '米纳',
    'Nolito': '诺利托',
    'Fabian Ruiz': '法比安·鲁伊斯',
    'Pablo Sarabia': '萨拉维亚',
    'Marco Asensio': '阿森西奥',
    'Mikel Merino': '梅里诺',
    'Mikel Oyarzabal': '奥亚萨瓦尔',
    'Alexander Isak': '伊萨克',
    'Alexander Sorloth': '瑟洛特',
    'Yeremy Pino': '皮诺',
    'Pau Torres': '保·托雷斯',
    'Diego Llorente': '迭戈·略伦特',
    'Jesus Navas': '赫苏斯·纳瓦斯',
    'Jose Gaya': '加亚',
    'Pedro Porro': '波罗',
    'Hugo Guillamon': '吉利亚蒙',
    'Carlos Soler': '索莱尔',
    'Marc Roca': '罗卡',
    'Brais Mendez': '布赖斯·门德斯',
    'Goncalo Guedes': '贡萨洛·格德斯',
    'Eden Hazard': '阿扎尔',
    'Thibaut Courtois': '库尔图瓦',
    'Jan Oblak': '奥布拉克',
    'Marc-Andre ter Stegen': '特尔施特根',

    # 法国球员
    'Wissam Ben Yedder': '本耶德尔',
    'Alexandre Lacazette': '拉卡泽特',
    'Antoine Griezmann': '格列兹曼',
    'Karim Benzema': '本泽马',
    'Kylian Mbappe': '姆巴佩',
    'Ousmane Dembele': '登贝莱',
    'Raphael Varane': '瓦拉内',
    'Paul Pogba': '博格巴',
    'N Golo Kante': '坎特',
    'Blaise Matuidi': '马图伊迪',
    'Adrien Rabiot': '拉比奥特',
    'Corentin Tolisso': '托利索',
    'Thomas Lemar': '勒马尔',
    'Kingsley Coman': '科曼',
    'Anthony Martial': '马夏尔',
    'Olivier Giroud': '吉鲁',
    'Karim Benzema': '本泽马',
    'Moussa Dembele': '穆萨·登贝莱',
    'Wissam Ben Yedder': '本耶德尔',
    'Andy Delort': '德洛尔',
    'Gaetan Laborde': '拉博德',
    'Martin Terrier': '泰里耶',
    'Benjamin Bourigeaud': '布里若',
    'Florian Thauvin': '托万',
    'Lucas Ocampos': '奥坎波斯',
    'Dimitri Payet': '帕耶',
    'Florian Wirtz': '维尔茨',
    'Jonathan Tah': '塔',
    'Piero Hincapie': '因卡皮耶',
    'Exequiel Palacios': '帕拉西奥斯',
    'Robert Andrich': '安德利希',
    'Jonas Hofmann': '霍夫曼',
    'Amine Adli': '阿德利',
    'Victor Boniface': '博尼法斯',
    'Patrik Schick': '希克',
    'Adam Hlozek': '赫洛热克',

    # 德国球员
    'Joshua Kimmich': '基米希',
    'Leon Goretzka': '格雷茨卡',
    'Ilkay Gundogan': '京多安',
    'Toni Kroos': '克罗斯',
    'Thomas Muller': '穆勒',
    'Leroy Sane': '萨内',
    'Serge Gnabry': '格纳布里',
    'Jamal Musiala': '穆西亚拉',
    'Kai Havertz': '哈弗茨',
    'Timo Werner': '维尔纳',
    'Timo Horn': '霍恩',
    'Kevin Trapp': '特拉普',
    'Bernd Leno': '莱诺',
    'Manuel Neuer': '诺伊尔',
    'Marc-Andre ter Stegen': '特尔施特根',
    'Dayot Upamecano': '于帕梅卡诺',
    'Matthijs de Ligt': '德里赫特',
    'Niklas Sule': '聚勒',
    'Antonio Rudiger': '吕迪格',
    'Jonathan Tah': '塔',
    'Nico Schlotterbeck': '施洛特贝克',
    'Mats Hummels': '胡梅尔斯',
    'Emre Can': '埃姆雷·詹',
    'Lukas Klostermann': '克洛斯特曼',
    'Benjamin Henrichs': '亨里希斯',
    'David Raum': '劳姆',
    'Christian Gunter': '金特',
    'Robin Gosens': '戈森斯',
    'Thilo Kehrer': '克雷尔',
    'Niklas Fulkrug': '菲尔克鲁格',
    'Thomas Muller': '穆勒',
    'Mario Gotze': '格策',
    'Julian Brandt': '布兰特',
    'Julian Draxler': '德拉克斯勒',
    'Max Meyer': '迈尔',
    'Leon Goretzka': '格雷茨卡',
    'Sebastian Rudy': '鲁迪',
    'Julian Weigl': '魏格尔',
    'Jonathan Tah': '塔',
    'Matthias Ginter': '金特尔',
    'Holger Badstuber': '巴德施图伯',
    'Jerome Boateng': '博阿滕',
    'Benedikt Howedes': '赫韦德斯',
    'Shkodran Mustafi': '穆斯塔菲',
    'Antonio Rudiger': '吕迪格',

    # 英格兰球员
    'Harry Kane': '凯恩',
    'Raheem Sterling': '斯特林',
    'Marcus Rashford': '拉什福德',
    'Jadon Sancho': '桑乔',
    'Phil Foden': '福登',
    'Bukayo Saka': '萨卡',
    'Jack Grealish': '格拉利什',
    'Mason Mount': '芒特',
    'Declan Rice': '赖斯',
    'Jude Bellingham': '贝林厄姆',
    'Jordan Henderson': '亨德森',
    'Trent Alexander-Arnold': '阿诺德',
    'Kyle Walker': '沃克',
    'Kieran Trippier': '特里皮尔',
    'Luke Shaw': '卢克·肖',
    'Ben Chilwell': '奇尔韦尔',
    'Harry Maguire': '马奎尔',
    'John Stones': '斯通斯',
    'Eric Dier': '戴尔',
    'Conor Coady': '科迪',
    'Kyle Walker-Peters': '沃克-彼得斯',
    'Aaron Ramsdale': '拉姆斯代尔',
    'Nick Pope': '波普',
    'Jordan Pickford': '皮克福德',
    'Sam Johnstone': '约翰斯通',
    'Fraser Forster': '福斯特',
    'Jack Butland': '巴特兰',
    'Tom Heaton': '希顿',
    'Lee Grant': '格兰特',
    'Wayne Rooney': '鲁尼',
    'Daniel Sturridge': '斯图里奇',
    'Danny Welbeck': '维尔贝克',
    'Rickie Lambert': '兰伯特',
    'Adam Lallana': '拉拉纳',
    'Jordan Henderson': '亨德森',
    'Steven Gerrard': '杰拉德',
    'Frank Lampard': '兰帕德',
    'Paul Scholes': '斯科尔斯',
    'David Beckham': '贝克汉姆',
    'Michael Owen': '欧文',
    'Emile Heskey': '赫斯基',
    'Peter Crouch': '克劳奇',
    'Jermain Defoe': '迪福',
    'Theo Walcott': '沃尔科特',
    'Ashley Young': '阿什利·扬',
    'James Milner': '米尔纳',
    'Gareth Barry': '巴里',
    'Scott Parker': '帕克',
    'Michael Carrick': '卡里克',
    'Owen Hargreaves': '哈格里夫斯',
    'Joe Cole': '乔·科尔',
    'Shaun Wright-Phillips': '赖特-菲利普斯',
    'Stewart Downing': '唐宁',
    'Ashley Cole': '阿什利·科尔',
    'Wayne Bridge': '布里奇',
    'Gary Neville': '加里·内维尔',
    'Phil Neville': '菲尔·内维尔',
    'Rio Ferdinand': '费迪南德',
    'John Terry': '特里',
    'Sol Campbell': '坎贝尔',
    'Ledley King': '金',
    'Jamie Carragher': '卡拉格',
    'Jonathan Woodgate': '伍德盖特',
    'Matthew Upson': '厄普森',
    'David James': '大卫·詹姆斯',
    'Robert Green': '格林',
    'Joe Hart': '乔·哈特',
    'Ben Foster': '福斯特',
    'Paul Robinson': '罗宾逊',
    'Chris Kirkland': '柯克兰',
    'Scott Carson': '卡森',

    # 波兰球员
    'Robert Lewandowski': '莱万多夫斯基',
    'Arkadiusz Milik': '米利克',
    'Krzysztof Piatek': '皮亚特克',
    'Piotr Zielinski': '泽林斯基',
    'Grzegorz Krychowiak': '克里霍维亚克',
    'Jakub Blaszczykowski': '布拉什奇科夫斯基',
    'Kamil Grosicki': '格罗西茨基',
    'Arkadiusz Milik': '米利克',
    'Wojciech Szczesny': '什琴斯尼',
    'Lukasz Fabianski': '法比安斯基',
    'Artur Boruc': '博鲁茨',
    'Lukasz Skorupski': '斯科鲁普斯基',
    'Bartosz Bereszynski': '贝雷辛斯基',
    'Jan Bednarek': '贝德纳雷克',
    'Thiago Cionek': '乔内克',
    'Michal Pazdan': '帕兹丹',
    'Kamil Glik': '格利克',
    'Maciej Rybus': '雷布斯',
    'Artur Jedrzejczyk': '耶德热伊奇克',
    'Pawel Dawidowicz': '达维多维奇',
    'Sebastian Walukiewicz': '瓦乌凯维奇',
    'Tomasz Kedziora': '肯齐奥拉',
    'Karol Linetty': '利内蒂',
    'Przemyslaw Frankowski': '弗兰科夫斯基',
    'Kamil Jozwiak': '约兹维亚克',
    'Damian Szymanski': '希曼斯基',
    'Mateusz Klich': '克利赫',
    'Sebastian Szymanski': '希曼斯基',
    'Jakub Moder': '莫德尔',
    'Kacper Kozlowski': '科兹沃夫斯基',
    'Nicolas Zalewski': '扎莱夫斯基',
    'Adam Buksa': '布克萨',
    'Karol Swiderski': '斯维德尔斯基',

    # 捷克球员
    'Petr Cech': '切赫',
    'Tomas Rosicky': '罗西基',
    'Pavel Nedved': '内德维德',
    'Jan Koller': '科勒',
    'Milan Baros': '巴罗什',
    'Vladimir Smicer': '斯米切尔',
    'Karel Poborsky': '波博斯基',
    'Tomas Hubschman': '许布施曼',
    'Rene Bolf': '博尔夫',
    'David Rozehnal': '罗泽纳尔',
    'Jaroslav Plasil': '普拉西尔',
    'David Jarolim': '亚罗利姆',
    'Tomas Galasek': '加拉塞克',
    'Zdenek Grygera': '格布雷-塞拉西',
    'Marek Jankulovski': '扬库洛夫斯基',
    'Tomas Ujfalusi': '乌伊法卢西',
    'Jan Polak': '波拉克',
    'Libor Sionko': '西翁科',
    'Martin Fenin': '费宁',
    'Vaclav Sverkos': '斯韦尔科什',
    'Daniel Zitka': '齐特卡',
    'Jaromir Blazek': '布拉热克',
    'Antonin Kinsky': '金斯基',
    'Matous Trmal': '特尔马尔',
    'Jindrich Stanek': '斯塔内克',
    'Vaclav Cerny': '切尔尼',
    'Ondrej Lingr': '林格尔',
    'Adam Hlozek': '赫洛热克',
    'Patrik Schick': '希克',
    'Tomas Soucek': '绍切克',
    'Vladimir Coufal': '曹法尔',
    'Tomas Kalas': '卡拉尔',
    'Ondrej Celustka': '切卢斯特卡',
    'David Zima': '齐马',
    'David Jurasek': '尤拉塞克',
    'David Doudera': '杜德拉',

    # 克罗地亚球员
    'Luka Modric': '莫德里奇',
    'Ivan Rakitic': '拉基蒂奇',
    'Mateo Kovacic': '科瓦契奇',
    'Marcelo Brozovic': '布罗佐维奇',
    'Ivan Perisic': '佩里西奇',
    'Mario Mandzukic': '曼朱基奇',
    'Nikola Kalinic': '卡利尼奇',
    'Andrej Kramaric': '克拉马里奇',
    'Marko Pjaca': '皮亚察',
    'Ante Rebic': '雷比奇',
    'Josip Brekalo': '布雷卡洛',
    'Bruno Petkovic': '佩特科维奇',
    'Ante Budimir': '布迪米尔',
    'Dejan Lovren': '洛夫伦',
    'Domagoj Vida': '维达',
    'Vedran Corluka': '乔尔卢卡',
    'Sime Vrsaljko': '弗尔萨利科',
    'Josip Juranovic': '尤拉诺维奇',
    'Borna Sosa': '索萨',
    'Josko Gvardiol': '格瓦迪奥尔',
    'Martin Erlic': '埃尔利奇',
    'Josip Stanisic': '斯塔尼希奇',
    'Borna Barisic': '巴里西奇',
    'Danijel Subasic': '苏巴西奇',
    'Lovre Kalinic': '卡利尼奇',
    'Dominik Livakovic': '利瓦科维奇',
    'Ivo Grbic': '格尔比奇',

    # 土耳其球员
    'Hakan Calhanoglu': '恰尔汗奥卢',
    'Arda Guler': '阿尔达·居莱尔',
    'Kenan Yildiz': '伊尔迪兹',
    'Cenk Tosun': '托松',
    'Burak Yilmaz': '伊尔马兹',
    'Enes Unal': '乌纳尔',
    'Yusuf Yazici': '亚兹哲',
    'Irfan Can Kahveci': '卡赫韦奇',
    'Orkun Kokcu': '科克曲',
    'Hakan Calhanoglu': '恰尔汗奥卢',
    'Ozan Tufan': '图凡',
    'Okay Yokuslu': '约库什卢',
    'Mahmut Tekdemir': '特克德米尔',
    'Dorukhan Tokoz': '托科兹',
    'Abdulkadir Omur': '奥穆尔',
    'Cengiz Under': '云代尔',
    'Kerem Akturkoglu': '阿克蒂尔克奥卢',
    'Yusuf Demir': '德米尔',
    'Halil Dervisoglu': '德尔维什奥卢',
    'Merih Demiral': '德米拉尔',
    'Caglar Soyuncu': '瑟云聚',
    'Ozan Kabak': '卡巴克',
    'Zeki Celik': '切利克',
    'Mert Muldur': '米尔德尔',
    'Umut Mersin': '梅尔辛',
    'Caner Erkin': '埃尔金',
    'Hasan Ali Kaldirim': '卡尔德勒姆',
    'Mert Gunok': '居诺克',
    'Altay Bayindir': '巴因迪尔',
    'Ugurcan Cakir': '恰克尔',
    'Fehmi Mert Gunok': '居诺克',

    # 俄罗斯球员
    'Artem Dzyuba': '久巴',
    'Aleksandr Golovin': '戈洛温',
    'Fedor Smolov': '斯莫洛夫',
    'Aleksandr Kokorin': '科科林',
    'Dmitri Poloz': '波洛兹',
    'Anton Zabolotny': '扎博洛特尼',
    'Artem Dzyuba': '久巴',
    'Denis Cheryshev': '切里舍夫',
    'Aleksandr Samedov': '萨梅多夫',
    'Roman Zobnin': '佐布宁',
    'Yuri Gazinsky': '加津斯基',
    'Alan Dzagoev': '扎戈耶夫',
    'Daler Kuzyaev': '库贾耶夫',
    'Roman Shirokov': '希罗科夫',
    'Igor Denisov': '杰尼索夫',
    'Dmitri Kombarov': '科姆巴罗夫',
    'Mario Fernandes': '费尔南德斯',
    'Vladimir Granat': '格拉纳特',
    'Ilya Kutepov': '库捷波夫',
    'Fedor Kudryashov': '库德里亚绍夫',
    'Sergei Ignashevich': '伊格纳舍维奇',
    'Andrei Semyonov': '谢苗诺夫',
    'Viktor Vasin': '瓦辛',
    'Georgi Dzhikiya': '吉基亚',
    'Igor Akinfeev': '阿金费耶夫',
    'Anton Shunin': '舒宁',
    'Andrei Lunev': '卢尼奥夫',
    'Soslan Dzhanaev': '贾纳耶夫',

    # 丹麦球员
    'Christian Eriksen': '埃里克森',
    'Kasper Schmeichel': '舒梅切尔',
    'Simon Kjaer': '克亚尔',
    'Andreas Christensen': '克里斯滕森',
    'Joakim Maehle': '梅勒',
    'Jens Stryger Larsen': '斯特赖格·拉森',
    'Daniel Wass': '瓦斯',
    'Thomas Delaney': '德莱尼',
    'Pierre-Emile Hojbjerg': '赫伊别尔',
    'Mathias Jensen': '延森',
    'Christian Norgaard': '诺尔高',
    'Mikkel Damsgaard': '达姆斯高',
    'Andreas Skov Olsen': '斯科夫·奥尔森',
    'Yussuf Poulsen': '波尔森',
    'Kasper Dolberg': '多尔贝里',
    'Martin Braithwaite': '布雷思韦特',
    'Andreas Cornelius': '科内柳斯',
    'Jonas Wind': '温德',
    'Anders Christiansen': '克里斯蒂安森',
    'Rasmus Kristensen': '克里斯滕森',
    'Joachim Andersen': '安德森',
    'Jannik Vestergaard': '韦斯特高',
    'Andreas Bjelland': '比耶兰',
    'Henrik Dalsgaard': '达尔高',
    'Zanka': '赞卡',
    'Nicolai Boilesen': '博伊莱森',
    'Victor Nelsson': '尼尔松',
    'Frederik Ronnow': '勒诺夫',
    'Oliver Christensen': '克里斯滕森',
    'Mads Hermansen': '赫尔曼森',

    # 日本球员
    'Takefusa Kubo': '久保建英',
    'Kaoru Mitoma': '三笘薰',
    'Wataru Endo': '远藤航',
    'Takehiro Tomiyasu': '富安健洋',
    'Hiroki Sakai': '酒井宏树',
    'Yuto Nagatomo': '长友佑都',
    'Maya Yoshida': '吉田麻也',
    'Ko Itakura': '板仓滉',
    'Shogo Taniguchi': '谷口彰悟',
    'Yuto Nagatomo': '长友佑都',
    'Hiroki Sakai': '酒井宏树',
    'Takehiro Tomiyasu': '富安健洋',
    'Miki Yamane': '山根视来',
    'Yuki Soma': '相马勇纪',
    'Hidemasa Morita': '守田英正',
    'Ao Tanaka': '田中碧',
    'Gaku Shibasaki': '柴崎岳',
    'Wataru Endo': '远藤航',
    'Ritsu Doan': '堂安律',
    'Junya Ito': '伊东纯也',
    'Takumi Minamino': '南野拓实',
    'Daichi Kamada': '镰田大地',
    'Ayase Ueda': '上田绮世',
    'Takuma Asano': '浅野拓磨',
    'Yuya Osako': '大迫勇也',
    'Shinji Okazaki': '冈崎慎司',
    'Yoshinori Muto': '武藤嘉纪',
    'Kyogo Furuhashi': '古桥亨梧',
    'Daizen Maeda': '前田大然',
    'Reo Hatate': '旗手怜央',
    'Shunsuke Nakamura': '中村俊辅',
    'Keisuke Honda': '本田圭佑',
    'Shinji Kagawa': '香川真司',
    'Makoto Hasebe': '长谷部诚',
    'Eiji Kawashima': '川岛永嗣',
    'Shuichi Gonda': '权田修一',
    'Daniel Schmidt': '施密特',
    'Zion Suzuki': '铃木彩艳',

    # 韩国球员
    'Son Heung-min': '孙兴慜',
    'Hwang Hee-chan': '黄喜灿',
    'Lee Kang-in': '李刚仁',
    'Kim Min-jae': '金玟哉',
    'Hwang In-beom': '黄仁范',
    'Lee Jae-sung': '李在城',
    'Kwon Chang-hoon': '权昶勋',
    'Na Sang-ho': '罗相镐',
    'Hwang Ui-jo': '黄义助',
    'Cho Gue-sung': '曹圭成',
    'Oh Hyeon-gyu': '吴贤揆',
    'Kim Young-gwon': '金英权',
    'Kim Min-jae': '金玟哉',
    'Kwon Kyung-won': '权敬原',
    'Kim Jin-su': '金珍洙',
    'Hong Chul': '洪喆',
    'Lee Yong': '李镕',
    'Kim Moon-hwan': '金文焕',
    'Park Ji-sung': '朴智星',
    'Ki Sung-yueng': '奇诚庸',
    'Koo Ja-cheol': '具滋哲',
    'Lee Chung-yong': '李青龙',
    'Park Chu-young': '朴主永',
    'Son Heung-min': '孙兴慜',
    'Kim Seung-gyu': '金承奎',
    'Jo Hyeon-woo': '赵贤祐',
    'Kim Jin-hyeon': '金镇铉',
    'Lee Beom-soo': '李范秀',
    'Song Bum-kon': '宋范根',

    # 瑞典球员
    'Zlatan Ibrahimovic': '伊布拉希莫维奇',
    'Alexander Isak': '伊萨克',
    'Dejan Kulusevski': '库卢塞夫斯基',
    'Emil Forsberg': '福斯贝里',
    'Viktor Claesson': '克拉松',
    'Sebastian Larsson': '拉尔森',
    'Albin Ekdal': '埃克达尔',
    'Kristoffer Olsson': '奥尔松',
    'Jens Cajuste': '卡尤斯特',
    'Emile Smith Rowe': '史密斯-罗',
    'Anthony Elanga': '埃兰加',
    'Dejan Kulusevski': '库卢塞夫斯基',
    'Alexander Isak': '伊萨克',
    'Viktor Gyokeres': '约克雷斯',
    'Robin Quaison': '夸伊松',
    'Marcus Berg': '贝里',
    'Ola Toivonen': '托伊沃宁',
    'John Guidetti': '圭代蒂',
    'Mikael Ishak': '伊沙克',
    'Victor Lindelof': '林德勒夫',
    'Andreas Granqvist': '格兰奎斯特',
    'Pontus Jansson': '扬松',
    'Mikael Lustig': '卢斯蒂格',
    'Ludwig Augustinsson': '奥古斯丁松',
    'Martin Olsson': '马丁·奥尔松',
    'Emil Krafth': '克拉夫特',
    'Filip Helander': '赫兰德',
    'Andreas Isaksson': '伊萨克松',
    'Robin Olsen': '奥尔森',
    'Karl-Johan Johnsson': '约翰松',

    # 瑞士球员
    'Xherdan Shaqiri': '沙奇里',
    'Granit Xhaka': '扎卡',
    'Manuel Akanji': '阿坎吉',
    'Ricardo Rodriguez': '罗德里格斯',
    'Stephan Lichtsteiner': '利希施泰纳',
    'Johan Djourou': '朱鲁',
    'Fabian Schar': '沙尔',
    'Manuel Akanji': '阿坎吉',
    'Nico Elvedi': '埃尔维迪',
    'Ricardo Rodriguez': '罗德里格斯',
    'Silvan Widmer': '威德默',
    'Kevin Mbabu': '姆巴布',
    'Jordan Lotomba': '洛通巴',
    'Edimilson Fernandes': '费尔南德斯',
    'Granit Xhaka': '扎卡',
    'Xherdan Shaqiri': '沙奇里',
    'Steven Zuber': '祖贝尔',
    'Valon Behrami': '贝赫拉米',
    'Gelson Fernandes': '费尔南德斯',
    'Blerim Dzemaili': '杰马伊利',
    'Haris Seferovic': '塞费罗维奇',
    'Breel Embolo': '恩博洛',
    'Mario Gavranovic': '加夫拉诺维奇',
    'Admir Mehmedi': '梅赫梅迪',
    'Ruben Vargas': '巴尔加斯',
    'Christian Fassnacht': '法斯纳赫特',
    'Yann Sommer': '索默',
    'Roman Burki': '布尔基',
    'Jonas Omlin': '奥姆林',
    'Gregor Kobel': '科贝尔',
    'Philipp Kohn': '科恩',

    # 美国球员
    'Christian Pulisic': '普利西奇',
    'Weston McKennie': '麦肯尼',
    'Giovanni Reyna': '雷纳',
    'Tyler Adams': '亚当斯',
    'Yunus Musah': '穆萨',
    'Brenden Aaronson': '阿伦森',
    'Tim Weah': '维阿',
    'Josh Sargent': '萨金特',
    'Ricardo Pepi': '佩皮',
    'Jesus Ferreira': '费雷拉',
    'Haji Wright': '赖特',
    'Jordan Pefok': '佩福克',
    'Daryl Dike': '戴克',
    'Matthew Hoppe': '霍普',
    'Konrad de la Fuente': '德拉富恩特',
    'Antonee Robinson': '罗宾逊',
    'Sergino Dest': '德斯特',
    'Walker Zimmerman': '齐默尔曼',
    'Miles Robinson': '罗宾逊',
    'John Brooks': '布鲁克斯',
    'Tim Ream': '里姆',
    'Aaron Long': '朗',
    'Mark McKenzie': '麦肯齐',
    'Chris Richards': '理查兹',
    'Cameron Carter-Vickers': '卡特-维克斯',
    'James Sands': '桑兹',
    'Joe Scally': '斯卡利',
    'DeAndre Yedlin': '耶德林',
    'Kellyn Acosta': '阿科斯塔',
    'Luca de la Torre': '德拉托雷',
    'Johnny Cardoso': '卡多索',
    'Malik Tillman': '蒂尔曼',
    'Zack Steffen': '斯特芬',
    'Matt Turner': '特纳',
    'Ethan Horvath': '霍瓦特',
    'Sean Johnson': '约翰逊',

    # 墨西哥球员
    'Raul Jimenez': '劳尔·希门尼斯',
    'Hirving Lozano': '洛萨诺',
    'Jesus Corona': '科罗纳',
    'Edson Alvarez': '阿尔瓦雷斯',
    'Hector Herrera': '埃雷拉',
    'Andres Guardado': '瓜尔达多',
    'Carlos Rodriguez': '罗德里格斯',
    'Orbelin Pineda': '皮内达',
    'Luis Romo': '罗莫',
    'Charly Rodriguez': '查理·罗德里格斯',
    'Alexis Vega': '维加',
    'Diego Lainez': '莱内斯',
    'Uriel Antuna': '安图尼亚',
    'Rogelio Funes Mori': '富内斯·莫里',
    'Henry Martin': '马丁',
    'Alexis Vega': '维加',
    'Raul Jimenez': '希门尼斯',
    'Javier Hernandez': '埃尔南德斯',
    'Carlos Vela': '贝拉',
    'Giovani dos Santos': '多斯桑托斯',
    'Jonathan dos Santos': '多斯桑托斯',
    'Miguel Layun': '拉云',
    'Nestor Araujo': '阿劳霍',
    'Hector Moreno': '莫雷诺',
    'Diego Reyes': '雷耶斯',
    'Jorge Sanchez': '桑切斯',
    'Jesus Gallardo': '加利亚多',
    'Guillermo Ochoa': '奥乔亚',
    'Alfredo Talavera': '塔拉韦拉',
    'Rodolfo Cota': '科塔',
    'Luis Malagon': '马拉贡',

    # 挪威球员
    'Erling Haaland': '哈兰德',
    'Martin Odegaard': '厄德高',
    'Sander Berge': '贝格',
    'Stefan Johansen': '约翰森',
    'Mathias Normann': '诺曼',
    'Mohamed Elyounoussi': '尤努西',
    'Markus Henriksen': '亨里克森',
    'Joshua King': '金',
    'Alexander Sorloth': '瑟洛特',
    'Ola Kamara': '卡马拉',
    'Mohamed Elyounoussi': '尤努西',
    'Kristoffer Ajer': '阿热',
    'Leo Ostigard': '厄斯蒂高',
    'Marius Lode': '洛德',
    'Birger Meling': '梅林',
    'Julian Ryerson': '赖尔森',
    'Omar Elabdellaoui': '阿卜杜勒劳伊',
    'Martin Linnes': '林内斯',
    'Sander Berge': '贝格',
    'Orjan Nyland': '尼兰',
    'Andre Hansen': '汉森',
    'Karl-Johan Johnsson': '约翰松',
}


def translate_players():
    """翻译球员名"""
    print("=" * 60)
    print("Translating More Player Names")
    print("=" * 60)

    conn = sqlite3.connect(DATABASE_PATH)
    cursor = conn.cursor()

    translated = 0
    not_found = 0

    for en_name, cn_name in PLAYER_NAMES.items():
        cursor.execute(
            "UPDATE players SET name_cn = ?, updated_at = datetime('now') WHERE name_en = ? AND name_cn IS NULL",
            (cn_name, en_name)
        )
        if cursor.rowcount > 0:
            translated += 1
            print(f"  {en_name} -> {cn_name}")
        else:
            not_found += 1

    conn.commit()

    # 统计
    cursor.execute("SELECT COUNT(*) FROM players WHERE name_cn IS NOT NULL")
    total_cn = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(*) FROM players")
    total = cursor.fetchone()[0]

    conn.close()

    print(f"\nTranslated: {translated}")
    print(f"Not found in DB: {not_found}")
    print(f"Total with Chinese: {total_cn}/{total} ({total_cn/total*100:.1f}%)")


if __name__ == '__main__':
    translate_players()
