#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
更多球员中文名词典 - 世界各国球员
"""

import os
import sys
import sqlite3
from pathlib import Path

if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

PROJECT_ROOT = Path(__file__).parent.parent
DATABASE_PATH = PROJECT_ROOT / 'data' / 'football_v2.db'

# 更多球员中文名词典
PLAYER_NAMES = {
    # 阿根廷球员
    'Claudio Lopez': '克劳迪奥·洛佩斯',
    'Hernan Crespo': '克雷斯波',
    'Jose Chamot': '查莫特',
    'Juan Pablo Sorin': '索林',
    'Juan Sebastian Veron': '贝隆',
    'Kily Gonzalez': '基利·冈萨雷斯',
    'Matias Almeyda': '阿尔梅达',
    'Carlos Tevez': '特维斯',
    'Fernando Gago': '加戈',
    'Ezequiel Lavezzi': '拉维奇',
    'Erik Lamela': '拉梅拉',
    'Giovani Lo Celso': '洛塞尔索',
    'Paulo Dybala': '迪巴拉',
    'Lautaro Martinez': '劳塔罗·马丁内斯',
    'Joaquin Correa': '华金·科雷亚',
    'Angel Correa': '安赫尔·科雷亚',
    'Lucas Ocampos': '奥坎波斯',
    'Giovanni Simeone': '西蒙尼',
    'Alejandro Gomez': '戈麦斯',
    'Nicolas Otamendi': '奥塔门迪',
    'German Pezzella': '佩泽拉',
    'Marcos Acuna': '阿库尼亚',
    'Nicolas Tagliafico': '塔利亚菲科',
    'Gonzalo Montiel': '蒙铁尔',
    'Juan Foyth': '福伊特',
    'Cristian Romero': '罗梅罗',
    'Lisandro Martinez': '利桑德罗·马丁内斯',
    'Guido Rodriguez': '罗德里格斯',
    'Leandro Paredes': '帕雷德斯',
    'Exequiel Palacios': '帕拉西奥斯',
    'Alexis Mac Allister': '麦卡利斯特',
    'Enzo Fernandez': '恩佐·费尔南德斯',
    'Emiliano Martinez': '埃米利亚诺·马丁内斯',
    'Franco Armani': '阿尔马尼',
    'Gerónimo Rulli': '鲁利',
    'Juan Musso': '穆索',
    'Agustin Marchesin': '马尔切辛',

    # 巴西球员
    'Cafu': '卡福',
    'Denilson': '德尼尔森',
    'Edmilson': '埃德米尔森',
    'Edilson': '埃迪尔森',
    'Gilberto Silva': '吉尔伯托·席尔瓦',
    'Kleberson': '克莱伯森',
    'Juliano Belletti': '贝莱蒂',
    'Juninho Paulista': '小儒尼尼奥',
    'Junior': '儒尼尼奥',
    'Luizao': '路易松',
    'Lucio': '卢西奥',
    'Marcos': '马科斯',
    'Ricardinho': '里卡迪尼奥',
    'Roberto Carlos': '罗伯特·卡洛斯',
    'Roque Junior': '罗克·儒尼奥尔',
    'Vampeta': '万佩塔',
    'Anderson Polga': '波尔加',
    'Maicon': '麦孔',
    'Dani Alves': '阿尔维斯',
    'Marcelo': '马塞洛',
    'David Luiz': '大卫·路易斯',
    'Thiago Silva': '蒂亚戈·席尔瓦',
    'Miranda': '米兰达',
    'Dante': '丹特',
    'Hernanes': '埃尔纳内斯',
    'Paulinho': '保利尼奥',
    'Fernandinho': '费尔南迪尼奥',
    'Luiz Gustavo': '古斯塔沃',
    'Ramires': '拉米雷斯',
    'Willian': '威廉',
    'Bernard': '伯纳德',
    'Hulk': '胡尔克',
    'Fred': '弗雷德',
    'Jo': '若',
    'Diego Costa': '迭戈·科斯塔',
    'Philippe Coutinho': '库蒂尼奥',
    'Roberto Firmino': '菲尔米诺',
    'Gabriel Jesus': '热苏斯',
    'Gabriel Barbosa': '加布里埃尔·巴尔博萨',
    'Richarlison': '理查利森',
    'Vinicius Junior': '维尼修斯',
    'Rodrygo': '罗德里戈',
    'Raphinha': '拉菲尼亚',
    'Antony': '安东尼',
    'Lucas Paqueta': '帕奎塔',
    'Bruno Guimaraes': '吉马良斯',
    'Casemiro': '卡塞米罗',
    'Fred': '弗雷德',
    'Allison': '阿利松',
    'Ederson': '埃德森',
    'Alisson Becker': '阿利松',
    'Weverton': '韦弗顿',
    'Neto': '内托',

    # 喀麦隆球员
    'Alioum Boukar': '布卡尔',
    'Bill Tchato': '恰托',
    'Daniel Ngom Kome': '科梅',
    'Geremi': '格雷米',
    'Joseph-Desire Job': '若布',
    'Lauren': '劳伦',
    'Marc-Vivien Foe': '福伊',
    'Patrick Mboma': '姆博马',
    'Patrick Suffo': '苏福',
    'Pierre Njanka': '尼扬卡',
    'Pierre Wome': '沃姆',
    'Pius Ndiefi': '恩迪菲',
    'Raymond Kalla': '卡拉',
    'Rigobert Song': '宋',
    'Salomon Olembé': '奥伦贝',
    'Samuel Etoo': '埃托奥',
    'Eric Maxim Choupo-Moting': '舒波-莫廷',
    'Karl Toko Ekambi': '托科·埃坎比',
    'Vincent Aboubakar': '阿布巴卡尔',
    'André Onana': '奥纳纳',
    'Fabrice Ondoa': '翁多阿',
    'Devis Epassy': '埃帕西',

    # 中国球员
    'Du Wei': '杜威',
    'Fan Zhiyi': '范志毅',
    'Hao Haidong': '郝海东',
    'Jiang Jin': '江津',
    'Li Tie': '李铁',
    'Li Weifeng': '李玮峰',
    'Li Xiaopeng': '李小鹏',
    'Ma Mingyu': '马明宇',
    'Qi Hong': '祁宏',
    'Qu Bo': '曲波',
    'Shao Jiayi': '邵佳一',
    'Sun Jihai': '孙继海',
    'Wu Chengying': '吴承瑛',
    'Xu Yunlong': '徐云龙',
    'Yang Chen': '杨晨',
    'Yu Genwei': '于根伟',
    'Zhang Enhua': '张恩华',
    'Zhang Xiaorui': '张效瑞',
    'Zhao Junzhe': '肇俊哲',
    'Zheng Zhi': '郑智',
    'Wu Lei': '武磊',
    'Zhang Linpeng': '张琳芃',
    'Wang Dalei': '王大雷',
    'Yan Junling': '颜骏凌',
    'Zhang Yuning': '张玉宁',
    'Wei Shihao': '韦世豪',
    'Huang Bowen': '黄博文',
    'Hao Junmin': '蒿俊闵',
    'Yu Dabao': '于大宝',
    'Feng Xiaoting': '冯潇霆',
    'Li Xuepeng': '李学鹏',
    'Gao Lin': '郜林',
    'Wu Xi': '吴曦',

    # 日本球员
    'Seigo Narazaki': '楢崎正刚',
    'Yoshikatsu Kawaguchi': '川口能活',
    'Ryuzo Morioka': '森冈隆三',
    'Koji Nakata': '名良桥晃',
    'Toshihiro Hattori': '服部年宏',
    'Hiroshi Nanami': '名波浩',
    'Shinji Ono': '小野伸二',
    'Junichi Inamoto': '稻本润一',
    'Kazuhiro Murakami': '村上和弘',
    'Atsushi Yanagisawa': '柳泽敦',
    'Takayuki Suzuki': '铃木隆行',
    'Masashi Nakayama': '中山雅史',
    'Naohiro Takahara': '高原直泰',
    'Yuji Nakazawa': '中泽佑二',
    'Tsuneyasu Miyamoto': '宫本恒靖',
    'Keiji Tamada': '玉田圭司',
    'Shunsuke Nakamura': '中村俊辅',
    'Koji Yamase': '山濑功治',
    'Mitsuo Ogasawara': '小笠原满男',
    'Yasuhito Endo': '远藤保仁',
    'Makoto Hasebe': '长谷部诚',
    'Yuto Nagatomo': '长友佑都',
    'Shinji Okazaki': '冈崎慎司',
    'Keisuke Honda': '本田圭佑',
    'Yoshito Okubo': '大久保嘉人',
    'Hiroshi Kiyotake': '清武弘嗣',
    'Maya Yoshida': '吉田麻也',
    'Gotoku Sakai': '酒井高德',
    'Hiroki Sakai': '酒井宏树',
    'Eiji Kawashima': '川岛永嗣',
    'Takehiro Tomiyasu': '富安健洋',
    'Wataru Endo': '远藤航',
    'Takefusa Kubo': '久保建英',
    'Kaoru Mitoma': '三笘薰',
    'Ritsu Doan': '堂安律',
    'Daichi Kamada': '镰田大地',
    'Takumi Minamino': '南野拓实',
    'Junya Ito': '伊东纯也',
    'Ayase Ueda': '上田绮世',
    'Zion Suzuki': '铃木彩艳',

    # 韩国球员
    'Kim Byung-ji': '金秉址',
    'Lee Woon-jae': '李云在',
    'Hong Myung-bo': '洪明甫',
    'Kim Tae-young': '金泰映',
    'Choi Jin-cheul': '崔镇哲',
    'Kim Min-jae': '金玟哉',
    'Lee Young-pyo': '李荣表',
    'Song Chong-gug': '宋钟国',
    'Choi Sung-yong': '崔成勇',
    'Park Ji-sung': '朴智星',
    'Lee Chun-soo': '李天秀',
    'Kim Nam-il': '金南一',
    'Yoo Sang-chul': '柳相铁',
    'Lee Eul-yong': '李乙容',
    'Seol Ki-hyeon': '薛琦铉',
    'Ahn Jung-hwan': '安贞焕',
    'Hwang Sun-hong': '黄善洪',
    'Cha Du-ri': '车杜里',
    'Park Chu-young': '朴主永',
    'Ki Sung-yueng': '奇诚庸',
    'Koo Ja-cheol': '具滋哲',
    'Son Heung-min': '孙兴慜',
    'Lee Chung-yong': '李青龙',
    'Kim Young-gwon': '金英权',
    'Kim Seung-gyu': '金承奎',
    'Jo Hyeon-woo': '赵贤祐',
    'Hwang Hee-chan': '黄喜灿',
    'Lee Kang-in': '李刚仁',
    'Hwang In-beom': '黄仁范',

    # 意大利球员
    'Gianluigi Buffon': '布冯',
    'Francesco Toldo': '托尔多',
    'Paolo Maldini': '马尔蒂尼',
    'Alessandro Nesta': '内斯塔',
    'Fabio Cannavaro': '卡纳瓦罗',
    'Alessandro Costacurta': '科斯塔库塔',
    'Marco Materazzi': '马特拉齐',
    'Andrea Barzagli': '巴尔扎利',
    'Giorgio Chiellini': '基耶利尼',
    'Leonardo Bonucci': '博努奇',
    'Gianluca Zambrotta': '赞布罗塔',
    'Fabio Grosso': '格罗索',
    'Massimo Oddo': '奥多',
    'Christian Panucci': '帕努奇',
    'Andrea Pirlo': '皮尔洛',
    'Gennaro Gattuso': '加图索',
    'Daniele De Rossi': '德罗西',
    'Simone Perrotta': '佩罗塔',
    'Mauro Camoranesi': '卡莫拉内西',
    'Antonio Cassano': '卡萨诺',
    'Francesco Totti': '托蒂',
    'Alessandro Del Piero': '德尔·皮耶罗',
    'Luca Toni': '托尼',
    'Alberto Gilardino': '吉拉迪诺',
    'Vincenzo Iaquinta': '亚昆塔',
    'Filippo Inzaghi': '因扎吉',
    'Marco Di Vaio': '迪瓦约',
    'Antonio Di Natale': '迪纳塔莱',
    'Fabio Quagliarella': '夸利亚雷拉',
    'Graziano Pelle': '佩莱',
    'Ciro Immobile': '因莫比莱',
    'Andrea Belotti': '贝洛蒂',
    'Lorenzo Insigne': '因西涅',
    'Domenico Berardi': '贝拉尔迪',
    'Federico Chiesa': '基耶萨',
    'Nicolo Zaniolo': '扎尼奥洛',
    'Sandro Tonali': '托纳利',
    'Nicolo Barella': '巴雷拉',
    'Manuel Locatelli': '洛卡特利',
    'Jorginho': '若日尼奥',
    'Marco Verratti': '维拉蒂',
    'Gianluigi Donnarumma': '多纳鲁马',

    # 荷兰球员
    'Edwin van der Sar': '范德萨',
    'Jasper Cillessen': '西莱森',
    'Tim Krul': '克鲁尔',
    'Michel Vorm': '弗姆',
    'Ron Vlaar': '弗拉尔',
    'Stefan de Vrij': '德弗里',
    'Bruno Martins Indi': '马丁斯·因迪',
    'Daley Blind': '布林德',
    'Gregory van der Wiel': '范德维尔',
    'Daryl Janmaat': '扬马特',
    'Terence Kongolo': '孔戈洛',
    'Memphis Depay': '德佩',
    'Arjen Robben': '罗本',
    'Wesley Sneijder': '斯内德',
    'Nigel de Jong': '德容',
    'Jonathan de Guzman': '德古兹曼',
    'Georginio Wijnaldum': '维纳尔杜姆',
    'Jordy Clasie': '克拉西',
    'Davy Klaassen': '克拉森',
    'Kevin Strootman': '斯特罗特曼',
    'Ibrahim Afellay': '阿费莱',
    'Jeremain Lens': '伦斯',
    'Quincy Promes': '普罗梅斯',
    'Klaas-Jan Huntelaar': '亨特拉尔',
    'Robin van Persie': '范佩西',
    'Dirk Kuyt': '库伊特',
    'Luuk de Jong': '卢克·德容',
    'Vincent Janssen': '扬森',
    'Ryan Babel': '巴贝尔',
    'Nathan Ake': '阿克',
    'Patrick van Aanholt': '范安霍尔特',
    'Denzel Dumfries': '邓弗里斯',
    'Jurrien Timber': '廷伯',
    'Cody Gakpo': '加克波',
    'Xavi Simons': '哈维·西蒙斯',
    'Virgil van Dijk': '范戴克',
    'Matthijs de Ligt': '德里赫特',
    'Frenkie de Jong': '德容',
    'Donny van de Beek': '范德贝克',
    'Steven Bergwijn': '贝格温',

    # 葡萄牙球员
    'Vitor Baia': '拜亚',
    'Ricardo': '里卡多',
    'Rui Patricio': '帕特里西奥',
    'Anthony Lopes': '安东尼·洛佩斯',
    'Rui Costa': '鲁伊·科斯塔',
    'Diogo Costa': '迪奥戈·科斯塔',
    'Fernando Couto': '库托',
    'Jorge Andrade': '安德拉德',
    'Ricardo Carvalho': '卡瓦略',
    'Bruno Alves': '布鲁诺·阿尔维斯',
    'Pepe': '佩佩',
    'Jose Fonte': '丰特',
    'Raphael Guerreiro': '格雷罗',
    'Nelson Semedo': '塞梅多',
    'Joao Cancelo': '坎塞洛',
    'Diogo Dalot': '达洛特',
    'Nuno Mendes': '努诺·门德斯',
    'Paulo Ferreira': '费雷拉',
    'Miguel': '米格尔',
    'Nuno Valente': '努诺·瓦伦特',
    'Deco': '德科',
    'Armando Petit': '佩蒂特',
    'Costinha': '科斯蒂尼亚',
    'Hugo Viana': '维亚纳',
    'Raul Meireles': '梅雷莱斯',
    'Miguel Veloso': '维洛索',
    'Joao Moutinho': '穆蒂尼奥',
    'Ruben Neves': '鲁本·内维斯',
    'William Carvalho': '威廉·卡瓦略',
    'Danilo Pereira': '达尼洛·佩雷拉',
    'Bruno Fernandes': '布鲁诺·费尔南德斯',
    'Bernardo Silva': '贝尔纳多·席尔瓦',
    'Joao Mario': '若昂·马里奥',
    'Andre Gomes': '安德烈·戈麦斯',
    'Renato Sanches': '雷纳托·桑切斯',
    'Luis Figo': '菲戈',
    'Cristiano Ronaldo': 'C罗',
    'Nani': '纳尼',
    'Ricardo Quaresma': '夸雷斯马',
    'Simao Sabrosa': '西芒',
    'Helder Postiga': '波斯蒂加',
    'Hugo Almeida': '阿尔梅达',
    'Liedson': '列德松',
    'Eder': '埃德尔',
    'Diogo Jota': '若塔',
    'Joao Felix': '若昂·菲利克斯',
    'Andre Silva': '安德烈·席尔瓦',
    'Goncalo Ramos': '贡萨洛·拉莫斯',
    'Rafael Leao': '莱奥',

    # 英格兰球员
    'David James': '大卫·詹姆斯',
    'David Seaman': '希曼',
    'Paul Robinson': '罗宾逊',
    'Robert Green': '格林',
    'Joe Hart': '乔·哈特',
    'Ben Foster': '福斯特',
    'Jordan Pickford': '皮克福德',
    'Nick Pope': '波普',
    'Aaron Ramsdale': '拉姆斯代尔',
    'Sam Johnstone': '约翰斯通',
    'Gary Neville': '加里·内维尔',
    'Phil Neville': '菲尔·内维尔',
    'Ashley Cole': '阿什利·科尔',
    'Wayne Bridge': '布里奇',
    'John Terry': '特里',
    'Rio Ferdinand': '费迪南德',
    'Sol Campbell': '坎贝尔',
    'Ledley King': '金',
    'Jamie Carragher': '卡拉格',
    'Jonathan Woodgate': '伍德盖特',
    'Matthew Upson': '厄普森',
    'Glen Johnson': '格伦·约翰逊',
    'Kyle Walker': '沃克',
    'Kieran Trippier': '特里皮尔',
    'Luke Shaw': '卢克·肖',
    'Ben Chilwell': '奇尔韦尔',
    'Harry Maguire': '马奎尔',
    'John Stones': '斯通斯',
    'Eric Dier': '戴尔',
    'Conor Coady': '科迪',
    'Tyrone Mings': '明斯',
    'Kyle Walker-Peters': '沃克-彼得斯',
    'Steven Gerrard': '杰拉德',
    'Frank Lampard': '兰帕德',
    'Paul Scholes': '斯科尔斯',
    'David Beckham': '贝克汉姆',
    'Joe Cole': '乔·科尔',
    'Shaun Wright-Phillips': '赖特-菲利普斯',
    'Owen Hargreaves': '哈格里夫斯',
    'Michael Carrick': '卡里克',
    'Scott Parker': '帕克',
    'James Milner': '米尔纳',
    'Jordan Henderson': '亨德森',
    'Declan Rice': '赖斯',
    'Jude Bellingham': '贝林厄姆',
    'Kalvin Phillips': '菲利普斯',
    'Mason Mount': '芒特',
    'Phil Foden': '福登',
    'Bukayo Saka': '萨卡',
    'Jack Grealish': '格拉利什',
    'Michael Owen': '欧文',
    'Wayne Rooney': '鲁尼',
    'Emile Heskey': '赫斯基',
    'Peter Crouch': '克劳奇',
    'Jermain Defoe': '迪福',
    'Theo Walcott': '沃尔科特',
    'Daniel Sturridge': '斯图里奇',
    'Danny Welbeck': '维尔贝克',
    'Harry Kane': '凯恩',
    'Jamie Vardy': '瓦尔迪',
    'Marcus Rashford': '拉什福德',
    'Raheem Sterling': '斯特林',
    'Jadon Sancho': '桑乔',
    'Trent Alexander-Arnold': '阿诺德',

    # 法国球员
    'Fabien Barthez': '巴特兹',
    'Gregory Coupet': '库佩',
    'Mickael Landreau': '朗德罗',
    'Hugo Lloris': '洛里',
    'Steve Mandanda': '曼丹达',
    'Mike Maignan': '迈尼昂',
    'Bixente Lizarazu': '利扎拉祖',
    'William Gallas': '加拉',
    'Marcel Desailly': '德塞利',
    'Lilian Thuram': '图拉姆',
    'Laurent Blanc': '布兰科',
    'Frank Leboeuf': '勒伯夫',
    'Vincent Candela': '坎德拉',
    'Willy Sagnol': '萨尼奥尔',
    'Eric Abidal': '阿比达尔',
    'Patrice Evra': '埃弗拉',
    'Bacary Sagna': '萨尼亚',
    'Gael Clichy': '克利希',
    'Laurent Koscielny': '科斯切尔尼',
    'Raphael Varane': '瓦拉内',
    'Samuel Umtiti': '乌姆蒂蒂',
    'Benjamin Pavard': '帕瓦尔',
    'Lucas Hernandez': '卢卡斯·埃尔南德斯',
    'Presnel Kimpembe': '金彭贝',
    'Dayot Upamecano': '于帕梅卡诺',
    'Jules Kounde': '孔德',
    'William Saliba': '萨利巴',
    'Didier Deschamps': '德尚',
    'Patrick Vieira': '维埃拉',
    'Emmanuel Petit': '佩蒂特',
    'Youri Djorkaeff': '德约卡夫',
    'Zinedine Zidane': '齐达内',
    'Robert Pires': '皮雷',
    'Thierry Henry': '亨利',
    'David Trezeguet': '特雷泽盖',
    'Sylvain Wiltord': '维尔托德',
    'Christophe Dugarry': '杜加里',
    'Nicolas Anelka': '阿内尔卡',
    'Djibril Cisse': '西塞',
    'Louis Saha': '萨哈',
    'Franck Ribery': '里贝里',
    'Florent Malouda': '马卢达',
    'Samir Nasri': '纳斯里',
    'Karim Benzema': '本泽马',
    'Antoine Griezmann': '格列兹曼',
    'Kylian Mbappe': '姆巴佩',
    'Ousmane Dembele': '登贝莱',
    'Paul Pogba': '博格巴',
    'NGolo Kante': '坎特',
    'Blaise Matuidi': '马图伊迪',
    'Adrien Rabiot': '拉比奥特',
    'Corentin Tolisso': '托利索',
    'Thomas Lemar': '勒马尔',
    'Kingsley Coman': '科曼',
    'Anthony Martial': '马夏尔',
    'Olivier Giroud': '吉鲁',
    'Alexandre Lacazette': '拉卡泽特',
    'Wissam Ben Yedder': '本耶德尔',
    'Aurelien Tchouameni': '楚阿梅尼',
    'Eduardo Camavinga': '卡马文加',

    # 德国球员
    'Oliver Kahn': '卡恩',
    'Jens Lehmann': '莱曼',
    'Manuel Neuer': '诺伊尔',
    'Marc-Andre ter Stegen': '特尔施特根',
    'Kevin Trapp': '特拉普',
    'Bernd Leno': '莱诺',
    'Timo Horn': '霍恩',
    'Andreas Kopke': '科普克',
    'Sepp Maier': '迈尔',
    'Berti Vogts': '福格茨',
    'Philipp Lahm': '拉姆',
    'Arne Friedrich': '弗里德里希',
    'Per Mertesacker': '默特萨克',
    'Mats Hummels': '胡梅尔斯',
    'Jerome Boateng': '博阿滕',
    'Holger Badstuber': '巴德施图伯',
    'Matthias Ginter': '金特尔',
    'Niklas Sule': '聚勒',
    'Antonio Rudiger': '吕迪格',
    'Jonathan Tah': '塔',
    'Nico Schlotterbeck': '施洛特贝克',
    'David Raum': '劳夫',
    'Christian Gunter': '金特',
    'Robin Gosens': '戈森斯',
    'Thilo Kehrer': '克雷尔',
    'Bastian Schweinsteiger': '施魏因斯泰格',
    'Michael Ballack': '巴拉克',
    'Torsten Frings': '弗林斯',
    'Thomas Hitzlsperger': '希茨尔斯佩格',
    'Tim Borowski': '博罗夫斯基',
    'Simon Rolfes': '罗尔费斯',
    'Sami Khedira': '赫迪拉',
    'Toni Kroos': '克罗斯',
    'Mesut Ozil': '厄齐尔',
    'Thomas Muller': '穆勒',
    'Lukas Podolski': '波多尔斯基',
    'Miroslav Klose': '克洛泽',
    'Mario Gomez': '戈麦斯',
    'Andre Schurrle': '许尔勒',
    'Julian Draxler': '德拉克斯勒',
    'Mario Gotze': '格策',
    'Leroy Sane': '萨内',
    'Serge Gnabry': '格纳布里',
    'Joshua Kimmich': '基米希',
    'Leon Goretzka': '格雷茨卡',
    'Ilkay Gundogan': '京多安',
    'Emre Can': '埃姆雷·詹',
    'Kai Havertz': '哈弗茨',
    'Jamal Musiala': '穆西亚拉',
    'Florian Wirtz': '维尔茨',
    'Timo Werner': '维尔纳',
    'Niklas Fullkrug': '菲尔克鲁格',

    # 西班牙球员
    'Iker Casillas': '卡西利亚斯',
    'Victor Valdes': '巴尔德斯',
    'Pepe Reina': '雷纳',
    'David De Gea': '德赫亚',
    'Kepa Arrizabalaga': '凯帕',
    'Unai Simon': '乌奈·西蒙',
    'Robert Sanchez': '罗伯特·桑切斯',
    'Carles Puyol': '普约尔',
    'Gerard Pique': '皮克',
    'Sergio Ramos': '拉莫斯',
    'Raul Albiol': '阿尔比奥尔',
    'Carlos Marchena': '马切纳',
    'Joan Capdevila': '卡普德维拉',
    'Alvaro Arbeloa': '阿韦洛亚',
    'Jordi Alba': '阿尔巴',
    'Dani Carvajal': '卡瓦哈尔',
    'Cesar Azpilicueta': '阿斯皮利奎塔',
    'Jose Gaya': '加亚',
    'Pedro Porro': '波罗',
    'Eric Garcia': '埃里克·加西亚',
    'Pau Torres': '保·托雷斯',
    'Aymeric Laporte': '拉波尔特',
    'Diego Llorente': '迭戈·略伦特',
    'Xabi Alonso': '阿隆索',
    'Sergio Busquets': '布斯克茨',
    'Xavi': '哈维',
    'Andres Iniesta': '伊涅斯塔',
    'David Silva': '大卫·席尔瓦',
    'Cesc Fabregas': '法布雷加斯',
    'Santi Cazorla': '卡索拉',
    'Juan Mata': '马塔',
    'Jesus Navas': '赫苏斯·纳瓦斯',
    'Pedro': '佩德罗',
    'Fernando Torres': '托雷斯',
    'David Villa': '比利亚',
    'Fernando Llorente': '略伦特',
    'Alvaro Negredo': '内格雷多',
    'Diego Costa': '迭戈·科斯塔',
    'Alvaro Morata': '莫拉塔',
    'Marco Asensio': '阿森西奥',
    'Rodri': '罗德里',
    'Pedri': '佩德里',
    'Gavi': '加维',
    'Ansu Fati': '法蒂',
    'Ferran Torres': '费兰·托雷斯',
    'Lamine Yamal': '亚马尔',
    'Nico Williams': '尼科·威廉姆斯',
    'Dani Olmo': '奥尔莫',
    'Mikel Oyarzabal': '奥亚萨瓦尔',
    'Iago Aspas': '阿斯帕斯',
    'Borja Iglesias': '伊格莱西亚斯',
}


def translate_players():
    """翻译球员名"""
    print("=" * 60)
    print("Translating World Player Names")
    print("=" * 60)

    conn = sqlite3.connect(DATABASE_PATH)
    cursor = conn.cursor()

    translated = 0
    not_found = 0

    for en_name, cn_name in PLAYER_NAMES.items():
        cursor.execute(
            "UPDATE players SET name_cn = ?, updated_at = datetime('now') WHERE name_en = ? AND name_cn IS NULL",
            (cn_name, en_name)
        )
        if cursor.rowcount > 0:
            translated += 1
            print(f"  {en_name} -> {cn_name}")
        else:
            not_found += 1

    conn.commit()

    # 统计
    cursor.execute("SELECT COUNT(*) FROM players WHERE name_cn IS NOT NULL")
    total_cn = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(*) FROM players")
    total = cursor.fetchone()[0]

    conn.close()

    print(f"\nTranslated: {translated}")
    print(f"Not found in DB: {not_found}")
    print(f"Total with Chinese: {total_cn}/{total} ({total_cn/total*100:.1f}%)")


if __name__ == '__main__':
    translate_players()
