# J联赛球队名映射 (繁体中文 -> 英文标准名)

# J1 League (日本J1联赛)
J1_TEAM_MAPPING = {
    '名古屋八鯨': 'Nagoya Grampus',
    '浦和紅鑽': 'Urawa Reds',
    '大阪飛腳': 'Gamba Osaka',
    '清水心跳': 'Shimizu S-Pulse',
    '大分三神': 'Oita Trinita',
    '橫濱水手': 'Yokohama F. Marinos',
    'FC東京': 'FC Tokyo',
    '神戶勝利船': 'Vissel Kobe',
    '柏雷素爾': 'Kashiwa Reysol',
    '千葉市原': 'JEF United Chiba',
    '鹿島鹿角': 'Kashima Antlers',
    '川崎前鋒': 'Kawasaki Frontale',
    '東京綠茵': 'Tokyo Verdy',
    '札幌岡薩多': 'Consadole Sapporo',
    '廣島三箭': 'Sanfrecce Hiroshima',
    '新潟天鵝': 'Albirex Niigata',
    '大宮松鼠': 'Omiya Ardija',
    '甲府風林': 'Ventforet Kofu',
    '福岡黃蜂': 'Avispa Fukuoka',
    '山形山神': 'Montedio Yamagata',
    '仙台維加泰': 'Vegalta Sendai',
    '鳥栖砂岩': 'Sagan Tosu',
    '湘南比馬': 'Shonan Bellmare',
    '磐田喜悅': 'Júbilo Iwata',
    '京都不死鳥': 'Kyoto Sanga',
    '大阪櫻花': 'Cerezo Osaka',
    '橫濱FC': 'Yokohama FC',
    '名古屋鯨魚': 'Nagoya Grampus',
    '浦和紅鑽': 'Urawa Reds',
    '大阪飛腳': 'Gamba Osaka',
    '清水鼓動': 'Shimizu S-Pulse',
    '大分三神': 'Oita Trinita',
    '橫濱水手': 'Yokohama F. Marinos',
    'FC東京': 'FC Tokyo',
    '神戶勝利船': 'Vissel Kobe',
    '柏雷素爾': 'Kashiwa Reysol',
    '千葉市原': 'JEF United Chiba',
    '鹿島鹿角': 'Kashima Antlers',
    '川崎前鋒': 'Kawasaki Frontale',
    '東京綠茵': 'Tokyo Verdy',
    '札幌岡薩多': 'Consadole Sapporo',
    '廣島三箭': 'Sanfrecce Hiroshima',
    '新潟天鵝': 'Albirex Niigata',
    '大宮松鼠': 'Omiya Ardija',
    '甲府風林': 'Ventforet Kofu',
    '福岡黃蜂': 'Avispa Fukuoka',
    '山形山神': 'Montedio Yamagata',
    '仙台維加泰': 'Vegalta Sendai',
    '鳥栖砂岩': 'Sagan Tosu',
    '湘南比馬': 'Shonan Bellmare',
    '磐田喜悅': 'Júbilo Iwata',
    '京都不死鳥': 'Kyoto Sanga',
    '大阪櫻花': 'Cerezo Osaka',
    # 英文名直接映射
    'Albirex Niigata': 'Albirex Niigata',
    'Avispa Fukuoka': 'Avispa Fukuoka',
    'Cerezo Osaka': 'Cerezo Osaka',
    'FC Machida Zelvia': 'FC Machida Zelvia',
    'FC Tokyo': 'FC Tokyo',
    'Fagiano Okayama': 'Fagiano Okayama',
    'Gamba Osaka': 'Gamba Osaka',
    'Hokkaido Consadole Sapporo': 'Consadole Sapporo',
    'Júbilo Iwata': 'Júbilo Iwata',
    'Kashima Antlers': 'Kashima Antlers',
    'Kashiwa Reysol': 'Kashiwa Reysol',
    'Kawasaki Frontale': 'Kawasaki Frontale',
    'Kyoto Sanga': 'Kyoto Sanga',
    'Kyoto Sanga FC': 'Kyoto Sanga',
    'Matsumoto Yamaga': 'Matsumoto Yamaga',
    'Mito HollyHock': 'Mito HollyHock',
    'Nagoya Grampus': 'Nagoya Grampus',
    'Oita Trinita': 'Oita Trinita',
    'Sagan Tosu': 'Sagan Tosu',
    'Sanfrecce Hiroshima': 'Sanfrecce Hiroshima',
    'Shimizu S-Pulse': 'Shimizu S-Pulse',
    'Shonan Bellmare': 'Shonan Bellmare',
    'Tokyo Verdy': 'Tokyo Verdy',
    'Urawa Red Diamonds': 'Urawa Reds',
    'Urawa Reds': 'Urawa Reds',
    'Vegalta Sendai': 'Vegalta Sendai',
    'Vissel Kobe': 'Vissel Kobe',
    'Yokohama F. Marinos': 'Yokohama F. Marinos',
    'Yokohama FC': 'Yokohama FC',
}

# J2 League (日本J2联赛)
J2_TEAM_MAPPING = {
    '札幌岡薩多': 'Consadole Sapporo',
    '仙台維加泰': 'Vegalta Sendai',
    '山形山神': 'Montedio Yamagata',
    '水戶蜀葵': 'Mito HollyHock',
    '大宮松鼠': 'Omiya Ardija',
    'FC東京': 'FC Tokyo',
    '東京綠茵': 'Tokyo Verdy',
    '川崎前鋒': 'Kawasaki Frontale',
    '湘南比馬': 'Shonan Bellmare',
    '甲府風林': 'Ventforet Kofu',
    '磐田喜悅': 'Júbilo Iwata',
    '清水心跳': 'Shimizu S-Pulse',
    '名古屋鯨魚': 'Nagoya Grampus',
    '京都不死鳥': 'Kyoto Sanga',
    '大阪櫻花': 'Cerezo Osaka',
    '大阪飛腳': 'Gamba Osaka',
    '神戶勝利船': 'Vissel Kobe',
    '廣島三箭': 'Sanfrecce Hiroshima',
    '新潟天鵝': 'Albirex Niigata',
    '福岡黃蜂': 'Avispa Fukuoka',
    '鳥栖砂岩': 'Sagan Tosu',
    '大分三神': 'Oita Trinita',
    '長崎成功丸': 'V-Varen Nagasaki',
    '熊本深紅': 'Roasso Kumamoto',
    '愛媛FC': 'Ehime FC',
    '岡山雉雞': 'Fagiano Okayama',
    '讚岐釜玉海': 'Kamatamare Sanuki',
    '德島漩渦': 'Tokushima Vortis',
    '藤枝MYFC': 'Azul Claro Numazu',
    '琉球FC': 'FC Ryukyu',
    '北九州向日葵': 'Giravanz Kitakyushu',
    '群馬草津溫泉': 'Thespakusatsu Gunma',
    '橫濱FC': 'Yokohama FC',
    '松本山雅': 'Matsumoto Yamaga',
    '金澤薩維根': 'Kataller Toyama',
    '秋田藍閃電': 'Blaublitz Akita',
    '岩手盛岡仙鹤': 'Iwate Grulla Morioka',
    # 英文名直接映射
    'Albirex Niigata': 'Albirex Niigata',
    'Avispa Fukuoka': 'Avispa Fukuoka',
    'Cerezo Osaka': 'Cerezo Osaka',
    'FC Machida Zelvia': 'FC Machida Zelvia',
    'FC Tokyo': 'FC Tokyo',
    'Fagiano Okayama': 'Fagiano Okayama',
    'Gamba Osaka': 'Gamba Osaka',
    'Júbilo Iwata': 'Júbilo Iwata',
    'Kashima Antlers': 'Kashima Antlers',
    'Kashiwa Reysol': 'Kashiwa Reysol',
    'Kawasaki Frontale': 'Kawasaki Frontale',
    'Kyoto Sanga': 'Kyoto Sanga',
    'Matsumoto Yamaga': 'Matsumoto Yamaga',
    'Mito HollyHock': 'Mito HollyHock',
    'Nagoya Grampus': 'Nagoya Grampus',
    'Oita Trinita': 'Oita Trinita',
    'Sagan Tosu': 'Sagan Tosu',
    'Sanfrecce Hiroshima': 'Sanfrecce Hiroshima',
    'Shimizu S-Pulse': 'Shimizu S-Pulse',
    'Shonan Bellmare': 'Shonan Bellmare',
    'Tokyo Verdy': 'Tokyo Verdy',
    'Urawa Reds': 'Urawa Reds',
    'Vegalta Sendai': 'Vegalta Sendai',
    'Vissel Kobe': 'Vissel Kobe',
    'Yokohama F. Marinos': 'Yokohama F. Marinos',
    'Yokohama FC': 'Yokohama FC',
    'V-Varen Nagasaki': 'V-Varen Nagasaki',
    'Roasso Kumamoto': 'Roasso Kumamoto',
    'Ehime FC': 'Ehime FC',
    'Kamatamare Sanuki': 'Kamatamare Sanuki',
    'Tokushima Vortis': 'Tokushima Vortis',
    'FC Ryukyu': 'FC Ryukyu',
    'Giravanz Kitakyushu': 'Giravanz Kitakyushu',
    'Thespakusatsu Gunma': 'Thespakusatsu Gunma',
    'Kataller Toyama': 'Kataller Toyama',
    'Blaublitz Akita': 'Blaublitz Akita',
    'Iwate Grulla Morioka': 'Iwate Grulla Morioka',
    'Azul Claro Numazu': 'Azul Claro Numazu',
    'SC Sagamihara': 'SC Sagamihara',
    'Nara Club': 'Nara Club',
    'Omiya Ardija': 'Omiya Ardija',
    'Ventforet Kofu': 'Ventforet Kofu',
    'Montedio Yamagata': 'Montedio Yamagata',
    'Consadole Sapporo': 'Consadole Sapporo',
}